### ISSUE TITLE
Provide a comparison to Clear Linux

### ISSUE THREAD

**Issue by WSLUser** [microsoft/CBL-Mariner#103]
The README seems to suggest similarities to Clear Linux.  Can you provide a detailed comparison between CBL-Mariner and Clear Linux? Performance benchmarks are part of it but also about security, update efficiency, etc.  I would also suggest switching to autospec made by Clear Linux for rpm generation and utilize their rpms prior to utilizing rpms from Fedora, EPEL, etc.

**Comment by jslobodzian** [comment]
CBL-Mariner is currently intended for first party needs as described in the Readme.  Closing this inactive thread.
