### ISSUE TITLE
rubygem-prometheus-client has undeclared dependency on rubygem-quantile

### ISSUE THREAD

**Issue by tofay** [microsoft/CBL-Mariner#1032]
The rubygem-prometheus-client spec doesn't declare any runtime dependencies: https://github.com/microsoft/CBL-Mariner/blob/1.0/SPECS/rubygem-prometheus-client/rubygem-prometheus-client.spec

But this gem depends on quantile: https://rubygems.org/gems/prometheus-client/versions/0.9.0

In order to use the prometheus-client gem I need to explicitly install rubygem-quantile.

**Comment by christopherco** [comment]
Mariner 1.0 is EOL. Closing this issue out. Please open a new issue against 2.0 if this still a problem
