### ISSUE TITLE
iptables has undeclared dependency on iana-etc

### ISSUE THREAD

**Issue by tofay** [microsoft/CBL-Mariner#1049]
https://github.com/microsoft/CBL-Mariner/pull/741 added an iptables rule to ip4save that contains `--dport ssh`.

This adds an undeclared dependency on iana-etc. If you create an image with iptables without also installing iana-etc then the iptables systemd service will fail, preventing a successful boot.

**Comment by PawelWMS** [comment]
Thank you for letting us know, Tom!

@christopherco, @danmihai1, @rlmenge: may I ask you to take a look at the spec for `iptables`?

**Comment by mfrw** [comment]
Not sure why #1069 getting merged did not auto close this issue :thinking:
