### ISSUE TITLE
rpm not found

### ISSUE THREAD

**Issue by sylviankahane** [microsoft/CBL-Mariner#1073]
Adding RPM to worker chroot: filesystem-1.1-7.cm1.x86_64.rpm.
Adding RPM to worker chroot: kernel-headers-5.10.42.1-1.cm1.noarch.rpm.
Adding RPM to worker chroot: glibc-2.28-18.cm1.x86_64.rpm.
Elevated install failed for package glibc-2.28-18.cm1.x86_64.rpm, aborting. Inspect /mnt/c/Users/sylvian/CBL-Mariner/build/logs/worker_chroot.log for more info. Did you hydrate the toolchain?
make: *** [/mnt/c/Users/sylvian/CBL-Mariner/toolkit/scripts/tools.mk:148: /mnt/c/Users/sylvian/CBL-Mariner/build/worker/worker_chroot.tar.gz] Error 1

From the log file:

Adding RPM to worker chroot: filesystem-1.1-7.cm1.x86_64.rpm.
Found full path for package filesystem-1.1-7.cm1.x86_64.rpm in /mnt/c/Users/sylvian/CBL-Mariner/build/rpm_cache/cache: (/mnt/c/Users/sylvian/CBL-Mariner/build/rpm_cache/cache/x86_64/filesystem-1.1-7.cm1.x86_64.rpm)
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
warning: /mnt/c/Users/sylvian/CBL-Mariner/build/rpm_cache/cache/x86_64/filesystem-1.1-7.cm1.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 3135ce90: NOKEY
Verifying packages...
Preparing packages...
filesystem-1.1-7.cm1.x86_64
Adding RPM to worker chroot: kernel-headers-5.10.42.1-1.cm1.noarch.rpm.
Found full path for package kernel-headers-5.10.42.1-1.cm1.noarch.rpm in /mnt/c/Users/sylvian/CBL-Mariner/build/rpm_cache/cache: (/mnt/c/Users/sylvian/CBL-Mariner/build/rpm_cache/cache/noarch/kernel-headers-5.10.42.1-1.cm1.noarch.rpm)
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
warning: /mnt/c/Users/sylvian/CBL-Mariner/build/rpm_cache/cache/noarch/kernel-headers-5.10.42.1-1.cm1.noarch.rpm: Header V4 RSA/SHA256 Signature, key ID 3135ce90: NOKEY
Verifying packages...
Preparing packages...
kernel-headers-5.10.42.1-1.cm1.noarch
Adding RPM to worker chroot: glibc-2.28-18.cm1.x86_64.rpm.
Found full path for package glibc-2.28-18.cm1.x86_64.rpm in /mnt/c/Users/sylvian/CBL-Mariner/build/rpm_cache/cache: (/mnt/c/Users/sylvian/CBL-Mariner/build/rpm_cache/cache/x86_64/glibc-2.28-18.cm1.x86_64.rpm)
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
warning: /mnt/c/Users/sylvian/CBL-Mariner/build/rpm_cache/cache/x86_64/glibc-2.28-18.cm1.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 3135ce90: NOKEY
Verifying packages...
Preparing packages...
glibc-2.28-18.cm1.x86_64
error: unpacking of archive failed on file /usr/libexec/getconf/POSIX_V6_LP64_OFF64;60d305a4: cpio: link failed - No such file or directory
error: glibc-2.28-18.cm1.x86_64: install failed
Elevated install failed for package glibc-2.28-18.cm1.x86_64.rpm, aborting. Inspect /mnt/c/Users/sylvian/CBL-Mariner/build/logs/worker_chroot.log for more info. Did you hydrate the toolchain?

**Comment by flaw** [comment]
I had the same issue, this error seems to be caused by trying to run the build in a folder over a network share. Probably something in with the chroot (symlinking perhaps?) doesn't work as expected leading to this error. 
I cloned the repo directly inside the VM and build worked.

**Comment by ddstreetmicrosoft** [comment]
can't reproduce this very old issue, closing. please reopen if still an issue.
