### ISSUE TITLE
Kubernetes support?

### ISSUE THREAD

**Issue by dennis-yemelyanov** [microsoft/CBL-Mariner#1091]
Is there an easy way to build an image with a single node ready-to-use Kubernetes instance running on it?

There seems to be a Kubernetes folder under SPECS: https://github.com/microsoft/CBL-Mariner/tree/1.0/SPECS/kubernetes

But it’s removed in this PR: https://github.com/microsoft/CBL-Mariner/pull/1003

How exactly does this work? Are there any examples showing how to enable Kubernetes?

**Comment by manaspal2** [comment]
Even i am looking for the same documentation. I installed upto this point following the guidelines of Kubernetes installation on Fedora

dnf module -y install cri-o
dnf install cri-o
systemctl enable --now crio
dnf install kubernetes-kubeadm
dnf install kubernetes-node
dnf install kubernetes-kubeadm
dnf install cri-tools
dnf install kubernetes-client
dnf install iproute

But after that what are the necessary steps to perform? Not able to find any pointer.

**Comment by christopherco** [comment]
Mariner 1.0 is EOL. Closing this issue out. Please open a new issue against 2.0 if this still a problem
