### ISSUE TITLE
oscap-docker from openscap package doesn't work

### ISSUE THREAD

**Issue by tofay** [microsoft/CBL-Mariner#1123]
I'm trying to use the oscap-docker tool from the openscap package.

The first problem I ran into was that I needed to install `openscap-python` in order for the oscap-docker tool to work:
```
Traceback (most recent call last):
  File "/usr/bin/oscap-docker", line 23, in <module>
    from oscap_docker_python.oscap_docker_util import OscapScan
ModuleNotFoundError: No module named 'oscap_docker_python'
```
That suggests openscap-python should be a dependency of openscap (or the oscap-docker tool should be packaged separately with a dependency on openscap-python).

After installing openscap-python, the second problem I ran into was that oscap-docker uses python 2, even though the openscap python code isn't python 2 compatible:
```
oscap-docker
Traceback (most recent call last):
  File "/usr/bin/oscap-docker", line 23, in <module>
    from oscap_docker_python.oscap_docker_util import OscapScan
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 27, in <module>
    from oscap_docker_python.get_cve_input import getInputCVE
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/get_cve_input.py", line 18, in <module>
    import urllib.parse
ImportError: No module named parse
```

**Comment by christopherco** [comment]
Mariner 1.0 is EOL. Closing this issue out. Please open a new issue against 2.0 if this still a problem
