### ISSUE TITLE
Error building iso image

### ISSUE THREAD

**Issue by Logof** [microsoft/CBL-Mariner#1132]
WARN[0008] tar: Удаляется начальный `/' из имен объектов 
WARN[0016] Skipping move. Source and destination are the same file (/home/user/CBL-Mariner/out/images/iso_initrd/iso-initrd.img.tar.gz). 
INFO[0016] [1/1] Converted (/home/user/CBL-Mariner/build/imagegen/iso_initrd/imager_output/rootfs) -> (/home/user/CBL-Mariner/out/images/iso_initrd/iso-initrd.img.tar.gz) 
make[1]: выход из каталога «/home/user/CBL-Mariner/toolkit»
INFO[0000] Building ISO under '/home/user/CBL-Mariner/build/imagegen/full/workspace'. 
WARN[0000] Unexpected: temporary ISO build path '/home/user/CBL-Mariner/build/imagegen/full/workspace' exists. Removing. 
INFO[0002] Preparing ISO's bootloaders.                 
WARN[0002] 3+0 записей получено                         
WARN[0002] 3+0 записей отправлено                       
WARN[0002] 3145728 байт (3,1 MB, 3,0 MiB) скопирован, 0,00925706 s, 340 MB/s 
INFO[0007] Generating ISO image under '/home/user/CBL-Mariner/out/images/full/full-1.0.20210714.1028.iso'. 
WARN[0007] Bad Option '-e' (error -1 BADFLAG).          
WARN[0007] Usage: mkisofs [options] [-find] file... [find expression] 
WARN[0007]                                              
WARN[0007] Use mkisofs -help                            
WARN[0007] to get a list all of valid options.          
WARN[0007]                                              
WARN[0007] Use mkisofs -find -help                      
WARN[0007] to get a list of all valid -find options.    
WARN[0007]                                              
WARN[0007] Most important Options:                      
WARN[0007] 	-posix-H		Follow sylinks encountered on command line 
WARN[0007] 	-posix-L		Follow all symlinks               
WARN[0007] 	-posix-P		Do not follow symlinks (default)  
WARN[0007] 	-o FILE, -output FILE	Set output file name  
WARN[0007] 	-R, -rock		Generate Rock Ridge directory information 
WARN[0007] 	-r, -rational-rock	Generate rationalized Rock Ridge directory info 
WARN[0007] 	-J, -joliet		Generate Joliet directory information 
WARN[0007] 	-print-size		Print estimated filesystem size and exit 
WARN[0007] 	-UDF			Generate UDF file system             
WARN[0007] 	-dvd-audio		Generate DVD-Audio compliant UDF file system 
WARN[0007] 	-dvd-video		Generate DVD-Video compliant UDF file system 
WARN[0007] 	-dvd-hybrid		Generate a hybrid (DVD-Audio/DVD-Video) compliant UDF file system 
WARN[0007] 	-iso-level LEVEL	Set ISO9660 level (1..3) or 4 for ISO9660 v 2 
WARN[0007] 	-V ID, -volid ID	Set Volume ID              
WARN[0007] 	-graft-points		Allow to use graft points for filenames 
WARN[0007] 	-M FILE, -prev-session FILE	Set path to previous session to merge 
PANI[0007] Command 'mkisofs' failed with error: exit status 255 
panic: (*logrus.Entry) 0xc000092d20

**Comment by mfrw** [comment]
Can you please provide more details of your environment, which OS and OS-Version are you using.
Also what is the version of `mkisofs` ?
Looking at the logs, the warning seems fishy:
```bash
INFO[0007] Generating ISO image under '/home/user/CBL-Mariner/out/images/full/full-1.0.20210714.1028.iso'.
WARN[0007] Bad Option '-e' (error -1 BADFLAG).
WARN[0007] Usage: mkisofs [options] [-find] file... [find expression]
```

**Comment by Logof** [comment]
mkisofs 3.02a09 (x86_64-unknown-linux-gnu)

**Comment by mfrw** [comment]
Building CBL-Mariner is validated on `Ubuntu 18.04`.
Can you please confirm you are using the same ?
Link to [prerequisites](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/building/prerequisites.md#requirements-were-validated-on-ubuntu-1804).

**Comment by ddstreetmicrosoft** [comment]
closing this old issue due to no response
