### ISSUE TITLE
Is Raspberry pi support? 

### ISSUE THREAD

**Issue by eleutherius** [microsoft/CBL-Mariner#1138]
Hi, I have RPI 3B.
Can I build  .img file for this  edge device?

**Comment by SED4906** [comment]
I'm trying to do the same but for an RPi 4. I'll let you know how that goes.

**Comment by zulhfreelancer** [comment]
@SED4906 does it work?

**Comment by SED4906** [comment]
Oh, I forgot about this; but for starters I don't know enough about the build system to do this.

**Comment by jslobodzian** [comment]
RPi is and edge device scenario and not currently supported.

**Comment by MSDNAndi** [comment]
I am confused by the mention of "RPi is an edge device scenario and not currently supported". of course RPi is an edge device scenario. Is that a reason for not supporting it? Or is the not supported statement independent and makes the "edge device scenario" statement irrelevant?
Why is it confusing me? Azure Percept is also an Edge Device scenario and Azure Percept DK runs CBL Mariner.

**Comment by jslobodzian** [comment]
CBL-Mariner is available to the community but intended for first party needs.  Edge device scenarios are currently out of scope.

**Comment by MSDNAndi** [comment]
But Azure Percept is an edge device scenario - or are you trying to say that it is out of scope for the context of the community?

**Comment by ohault** [comment]
According to latest BUILD 2022 sessions and discussions, it looks like Edge device scenarios is now part of the scope for Mariner.Can you please re-open this ticket?

**Comment by ohault** [comment]
This is also very important to run k8s/k3s and Azure container technologies on Raspberry PI.
