### ISSUE TITLE
Fails in Build Tools

### ISSUE THREAD

**Issue by ArchieTsai** [microsoft/CBL-Mariner#114]
Hi team, 

I am new to CBL-Mariner. I followed the Prerequisites doc to install all the requirements for building. Then, run the command below to build tools as docs mentioned.

> sudo make toolchain REBUILD_TOOLS=y REBUILD_TOOLCHAIN=y DOWNLOAD_SRPMS=y

Almost 2 hours later, got the following error

![Screenshot 2020-09-18 153732](https://user-images.githubusercontent.com/13379695/93570112-1ab27d00-f9c5-11ea-93e0-178dc9ff5c78.png)

My dev environment is:
- Ubuntu 18.04 @ WSL2
- Docker desktop v2.3.0.5 for Windows
- commit ID: 83de3e225d554f749ea3a56c700e9c644afbe999 @ main branch

**Comment by WSLUser** [comment]
Try following this for GO instead: https://github.com/WhitewaterFoundry/pengwin-setup/blob/master/pengwin-setup.d/go.sh

**Comment by dmcilvaney** [comment]
Some updates to the quick start and other build guides were just completed in the 1.0-dev branch (https://github.com/microsoft/CBL-Mariner/blob/1.0-dev/toolkit/docs/building/building.md). We can't guarantee package/source availability for the tip of the branches, so the instructions now include `git checkout 1.0-stable`.

**Comment by nunix** [comment]
and a quick tip (not sure it applies to all), but I'm also using WSL2 Ubuntu 18.04 and `python2` is missing when building the packages.
So here is a quick workaround (might be needed to be added to the prerequisites page):
```bash
# Current Python v2 is 2.7
sudo apt install -y python2.7
sudo ln -s /usr/bin/python2.7 /usr/bin/python2
```

then building the packages `sudo make input-srpms DOWNLOAD_SRPMS=y` will no more throw this error.

And thanks for the additional git commands, the tools and packages built perfectly 👐

**Comment by jslobodzian** [comment]
Closing this issue as the original concern has been addressed.
