### ISSUE TITLE
During installation libc.so.6: version `GLIBC_2.32' not found issue

### ISSUE THREAD

**Issue by mirlanimash** [microsoft/CBL-Mariner#1149]
Built the ISO image. While trying to install getting this error:
./liveinstaller: /lib/libc.so.6: version `GLIBC_2.32' not found (required by ./liveinstaller)

and stuck in root account:
root [ /installer ]#

Ubuntu release where I built ISO image is 21.04.

**Comment by PawelWMS** [comment]
Thanks for letting us know, @mirlanimash! My first suggestion would be to re-try on Ubuntu 18.04 - that's the only build host we're currently supporting. Also, please double-check all [other build requirements](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/building/prerequisites.md). Make sure you're building off the `1.0-stable` tag!

If things still don't work, please get back to us with the full build commands you were running.

**Comment by mirlanimash** [comment]
@PawelWMS Thanks for the reply. I tried to fulfil the requirements on Ubuntu 18.04, but after the first command: "sudo add-apt-repository ppa:longsleep/golang-backports" it gives this output:

"Golang 1.8, 1.9, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15 and 1.16 PPA for Ubuntu
 More info: https://launchpad.net/~longsleep/+archive/ubuntu/golang-backports
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Error: retrieving gpg key timed out."

After I tried to still run: "sudo apt-get update" and it has these issues:

"Get:5 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu bionic InRelease [15.4 kB]
Err:5 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F6BC817356A3D45E
Hit:6 http://us.archive.ubuntu.com/ubuntu bionic InRelease"

and at lower part additionally:

"W: GPG error: http://ppa.launchpad.net/longsleep/golang-backports/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F6BC817356A3D45E
E: The repository 'http://ppa.launchpad.net/longsleep/golang-backports/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details."

I understand that these issues are related to Ubuntu side, but this message "[Requirements were validated on Ubuntu 18.04](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/building/prerequisites.md)" made me confident that I can try to build ISO image.
I think I just need to wait for downloadable ISO image for CBL-Mariner and test it later.

**Comment by putnamca** [comment]
> Thanks for letting us know, @mirlanimash! My first suggestion would be to re-try on Ubuntu 18.04 - that's the only build host we're currently supporting. Also, please double-check all [other build requirements](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/building/prerequisites.md). Make sure you're building off the `1.0-stable` tag!
> 
> If things still don't work, please get back to us with the full build commands you were running.

Seeing the same issue on 21.04. Unfortunately, I can't revert, as this is my "bleeding edge" WSL2 environment. If I need to, I'll spin up a VM or a container with Ubuntu 18.04 on it.

I will be playing around a little first, to see if I can find a workaround/fix.

**Comment by putnamca** [comment]
Made a Hyper-V VM with Ubuntu 18.04. Built a CBL-Mariner ISO, and installed it, on Hyper-V. This all went perfectly. Still impatient for a build that can be validated on 21.04 Ubuntu, but, meh. I am over-the-moon excited about the potential for CBL-Mariner. So cool. Dev team - kudos. Make it build on bleeding edge Ubuntu, and the world will embrace it, even faster.

Great job!

**Comment by putnamca** [comment]
I should have mentioned, for the Microsoft people - this is all on Windows 11. Bleeding edge is bleeding edge, after all.

**Comment by putnamca** [comment]
![Screenshot 2021-07-17 172608](https://user-images.githubusercontent.com/116844/126059263-5bd860ae-9c88-41af-9dd9-bc1b66dc7686.png)

**Comment by Biledaemon** [comment]
same as @mirlanimash :  

Built the ISO image. While trying to install getting this error:
./liveinstaller: /lib/libc.so.6: version `GLIBC_2.32' not found (required by ./liveinstaller)

and stuck in root account:
root [ /installer ]#

Built on Pop!_OS 21.04

I reckon @putnamca bleeding edge it is. Hopefully 21.04 will make it main.

**Comment by mirlanimash** [comment]
> Made a Hyper-V VM with Ubuntu 18.04. Built a CBL-Mariner ISO, and installed it, on Hyper-V. This all went perfectly. Still impatient for a build that can be validated on 21.04 Ubuntu, but, meh. I am over-the-moon excited about the potential for CBL-Mariner. So cool. Dev team - kudos. Make it build on bleeding edge Ubuntu, and the world will embrace it, even faster.
> 
> Great job!
@putnamce

How were you able to build? I had a lot of error messages even on Ubuntu 18.04. Detailed is in my reply above.

**Comment by Biledaemon** [comment]
> > Made a Hyper-V VM with Ubuntu 18.04. Built a CBL-Mariner ISO, and installed it, on Hyper-V. This all went perfectly. Still impatient for a build that can be validated on 21.04 Ubuntu, but, meh. I am over-the-moon excited about the potential for CBL-Mariner. So cool. Dev team - kudos. Make it build on bleeding edge Ubuntu, and the world will embrace it, even faster.
> > Great job!
> > @putnamce
> 
> How were you able to build? I had a lot of error messages even on Ubuntu 18.04. Detailed is in my reply above.

I followed  the required dependencies and the build was successful on 21.04.

**Comment by tingyin-duan** [comment]
> > > Made a Hyper-V VM with Ubuntu 18.04. Built a CBL-Mariner ISO, and installed it, on Hyper-V. This all went perfectly. Still impatient for a build that can be validated on 21.04 Ubuntu, but, meh. I am over-the-moon excited about the potential for CBL-Mariner. So cool. Dev team - kudos. Make it build on bleeding edge Ubuntu, and the world will embrace it, even faster.
> > > Great job!
> > > @putnamce
> > 
> > 
> > How were you able to build? I had a lot of error messages even on Ubuntu 18.04. Detailed is in my reply above.
> 
> I followed the required dependencies and the build was successful on 21.04.

Could you provide more details to make it work on 21.04?

**Comment by Biledaemon** [comment]
> > > > Made a Hyper-V VM with Ubuntu 18.04. Built a CBL-Mariner ISO, and installed it, on Hyper-V. This all went perfectly. Still impatient for a build that can be validated on 21.04 Ubuntu, but, meh. I am over-the-moon excited about the potential for CBL-Mariner. So cool. Dev team - kudos. Make it build on bleeding edge Ubuntu, and the world will embrace it, even faster.
> > > > Great job!
> > > > @putnamce
> > > 
> > > 
> > > How were you able to build? I had a lot of error messages even on Ubuntu 18.04. Detailed is in my reply above.
> > 
> > 
> > I followed the required dependencies and the build was successful on 21.04.
> 
> Could you provide more details to make it work on 21.04?
https://github.com/microsoft/CBL-MarinerDemo#Prequisites-Prepare-your-Environment

https://github.com/microsoft/CBL-MarinerDemo  -- it will build the iso just as well as CBL-Mariner but once the .iso is generated and you try to mount it (e.g. Virtualbox), you will get a CLI root /installer error: "version 'GLIBC_2.32' was not found (required by ./liveinstaller)

**Comment by tingyin-duan** [comment]
This problem may not caused totally by the difference. On 18.04 , I met the same problem. However, after I   do  more two steps,  'isohybrid -u *.iso' and ' implantisomd5 *.iso ' , the iso image can be installed on my computer using rufus to create a usb booter.

**Comment by jslobodzian** [comment]
closing issue as building with 18.04 per instructions is the current guidance and the build was successful after doing so.
