### ISSUE TITLE
Update building pre-reqs to use GO from github, not backport PPA

### ISSUE THREAD

**Issue by WSLUser** [microsoft/CBL-Mariner#115]
Use slightly modified version of `https://github.com/WhitewaterFoundry/pengwin-setup/blob/master/pengwin-setup.d/go.sh` instead of `ppa:longsleep/golang-backports`. 

This also removes need for this line since proper exports for env vars and $PATH are done in the script: 

> # Fix go 1.13 link
>  sudo ln -vs /usr/lib/go-1.13/bin/go /usr/bin/go

**Comment by thcrain-msft** [comment]
Thanks for opening the issue! Assigning this to myself- will spin up a script to handle installation using tarballs from https://golang.org/dl/ and handle proper exports for env vars/$PATH.

**Comment by christopherco** [comment]
Prereqs should be up to date. Closing this out, but do let us know if this is still an issue
