### ISSUE TITLE
Create an ISO file

### ISSUE THREAD

**Issue by gizamichal** [microsoft/CBL-Mariner#1165]
Hi, I've followed all steps in [prerequisites.md](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/building/prerequisites.md) and [quickstart.md](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/quick_start/quickstart.md). I understand the ISO builder is isomaker from CBL-Mariner/toolkit/out/tools directory.

When I execute ./isomaker, I'm getting:

_isomaker: error: required flag --build-dir not provided, try --help_

Can you explain how to use this command correctly?

**Comment by PawelWMS** [comment]
Hey Michał,

The `isomaker` is an internal tool call inside our `make` files and it's not intended to be run manually.  While, naturally, possible, the number of expected input arguments and the tool's expectations regarding the state of the build and existence of files under specific paths makes it very "unfriendly".

In short: if you'd like to build CBL-Mariner images/packages, please do it through the `make` targets mentioned in the documentation. If you'd like to play around with the tools individually, you're on your own. :)

**Comment by gizamichal** [comment]
> Hey Michał,
> 
> The `isomaker` is an internal tool call inside our `make` files and it's not intended to be run manually. While, naturally, possible, the number of expected input arguments and the tool's expectations regarding the state of the build and existence of files under specific paths makes it very "unfriendly".
> 
> In short: if you'd like to build CBL-Mariner images/packages, please do it through the `make` targets mentioned in the documentation. If you'd like to play around with the tools individually, you're on your own. :)

OK, I see appropriate file. Thank you :)
