### ISSUE TITLE
Providing network config

### ISSUE THREAD

**Issue by flaw** [microsoft/CBL-Mariner#1173]
I noticed that you by default disable the network configuration support in cloud-init.

I tried to use a post-install script to remove the 99-disable-network-config.cfg which did _something_, but not what I wanted it to do. I can see now in cloud-init logs that it is indeed trying to configure the network now as the meta-data instructs but that doesn't seem to result in the system actually having any configuration under /etc/systemd/network.

From this I'm assuming there is some other mechanism I should be using to provide the network configuration to Mariner? Could you point me in the right direction?

**Comment by universal4** [comment]
I am not sure what others may do, but I installed it as a vm, and network configured with dhcp.
Ifconfig worked to set an ip temporary, but it went back to default dhcp upon reboot.

After it was set up, I created 2 new config files for the public and private cards and it works fine that way.
In the config files I just named the nic in the match section (eth0 or eth1)
Then in network section, the normal address and gateway and dns lines, for the private only an address and netmask line was needed
The config files need to be named lower numbers then the 99, but once I verified it worked, I got rid of the 99 one.

**Comment by ddstreetmicrosoft** [comment]
in mariner 3 (azure linux 3), cloud-init default network configuration is restored. for mariner 2, when running in azure, the cloud-init datasource should provide the network configuration details, and when running outside a cloud environment, you can either use the `99-dhcp-en.network` file (which enables DHCP for all interfaces that start with the letter 'e'), or if that doesn't work for you then you will need to create your own systemd-networkd configuration file.
