### ISSUE TITLE
Auto-provisioning using ISO?

### ISSUE THREAD

**Issue by p5** [microsoft/CBL-Mariner#1177]
Is there any way to auto-install CBL-Mariner installation using an ISO and user-data & meta-data files?  

I have tried creating a "meta-user-data.iso" file using the attached files (appended .txt extension so GitHub would allow them) with the following command:
`
genisoimage -output meta-user-data.iso -volid cidata -rock user-data meta-data
`

The command produced an ISO output but when supplying this with the main ISO, I am just stuck on the usual selection for how to install - Graphical/Terminal/Terminal with speech.

If this is not available currently, it is something which would be extremely useful as there are only a handful of these sorts of distributions available. It would make it much easier to provision these virtual machines using Terraform.

I appreciate what you are doing for the Linux community.  This release was a pleasant surprise.  

[meta-data.txt](https://github.com/microsoft/CBL-Mariner/files/6865680/meta-data.txt)
[user-data.txt](https://github.com/microsoft/CBL-Mariner/files/6865681/user-data.txt)

**Comment by thcrain-msft** [comment]
Hi @p5, thanks for the kind words! 

Our meta-data and user-data cloudinit files are not used for the ISO installer. To create an unattended ISO installer image, please refer to the [last paragraph of this section of our documentation](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/building/building.md#iso-images).

**Comment by p5** [comment]
Thank you.  Not quite sure how I missed that.
