### ISSUE TITLE
httpd start failed

### ISSUE THREAD

**Issue by gizamichal** [microsoft/CBL-Mariner#1179]
Hi, I found a minor bug. There is no logs directory in /var, only a log directory. This makes the HTTP server unable to start.

sudo yum install httpd
sudo systemctl start httpd

```
Jul 23 10:17:37 cbl-mariner httpd[630]: (2)No such file or directory: AH02291: Cannot access directory '/var/logs/' for main error log
Jul 23 10:17:37 cbl-mariner httpd[630]: AH00014: Configuration check failed
Jul 23 10:17:37 cbl-mariner systemd[1]: httpd.service: Control process exited, code=exited status=1
Jul 23 10:17:37 cbl-mariner systemd[1]: httpd.service: Failed with result 'exit-code'.
Jul 23 10:17:37 cbl-mariner systemd[1]: Failed to start The Apache HTTP Server.
```

It was enough to create this directory, and it works.

sudo mkdir /var/logs
sudo systemctl start httpd

**Comment by PawelWMS** [comment]
Ah, thank you for catching that! It looks like we might need to modify how we build `httpd` so that by default it's configured to use an existing directory.
