### ISSUE TITLE
sos is packaged but is not functional on CBL-Mariner

### ISSUE THREAD

**Issue by TurboTurtle** [microsoft/CBL-Mariner#1185]
I'm the lead maintainer for [sos](https://github.com/sosreport/sos) which I see [is packaged](https://github.com/microsoft/CBL-Mariner/tree/1.0/SPECS/sos) in CBL-Mariner.

However, as sos functions based on what the project calls distribution policies to define how to enable plugins and perform collections, it is not currently functional for CBL-Mariner.

We would be more than happy to help extend support in sos for Mariner, but my question is if this is desired given the internal use case of Mariner versus the nature of sos which is to collect diagnostic information for troubleshooting (almost always with a technical support vendor).

If so we can probably create a new sos policy fairly quickly, and in time for our next upstream release, sos-4.2, which is due to close in mid August.

**Comment by earls0011** [comment]
Hi need help with a google account please contact earls0011@outlook.com

**Comment by thcrain-msft** [comment]
Hi @TurboTurtle, thank you for the offer! A distro-specific policy for CBL-Mariner would be appropriate for our use case. I've self-assigned this, and I'll go ahead and get a rudimentary policy created in line with other distro policies present in `sos`. I will update this issue when a PR against `sos` is created.

**Comment by christopherco** [comment]
Tagging @eric-desrochers for his contributions to add Azure Linux to the `sos` project. We're looking forward to enabling plugins and expand the Azure Linux policy in the upstream `sos` project

**Comment by eric-desrochers** [comment]
A policy has been created in sos upstream last April/Mai: 
https://github.com/sosreport/sos/pulls?q=is%3Apr+mariner+is%3Aclosed

We are indeed looking forward to enable plugins for Azure Linux.
