### ISSUE TITLE
Toolchain download failure - 404 errors

### ISSUE THREAD

**Issue by elsaco** [microsoft/CBL-Mariner#1191]
While trying to build the ISO, kernel-headers package fails to download. Not sure if there are other RPMs that end in 404 error. This is the first 404  (not found) encountered and the script terminates.

Here's sample output:
---cut---
Downloading toolchain RPM: filesystem-1.1-7.cm1.x86_64.rpm
Downloading toolchain RPM: kernel-headers-5.10.52.1-1.cm1.noarch.rpm

ERROR: Failed to download toolchain package: kernel-headers-5.10.52.1-1.cm1.noarch.rpm.
ERROR: Last 20 lines from log '/home/ubuntu/CBL-Mariner/build/logs/toolchain/downloads/kernel-headers-5.10.52.1-1.cm1.noarch.rpm.log':

        Downloading toolchain RPM: kernel-headers-5.10.52.1-1.cm1.noarch.rpm
        --2021-07-26 22:59:15--  https://packages.microsoft.com/cbl-mariner/1.0/prod/base/x86_64/rpms/kernel-headers-5.10.52.1-1.cm1.noarch.rpm
        Resolving packages.microsoft.com (packages.microsoft.com)... 13.93.152.112
        Connecting to packages.microsoft.com (packages.microsoft.com)|13.93.152.112|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2021-07-26 22:59:15 ERROR 404: Not Found.

        --2021-07-26 22:59:15--  https://packages.microsoft.com/cbl-mariner/1.0/prod/update/x86_64/rpms/kernel-headers-5.10.52.1-1.cm1.noarch.rpm
        Resolving packages.microsoft.com (packages.microsoft.com)... 13.93.152.112
        Connecting to packages.microsoft.com (packages.microsoft.com)|13.93.152.112|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2021-07-26 22:59:15 ERROR 404: Not Found.

**Comment by PawelWMS** [comment]
Hey there,

Please double-check, if you got the toolkit from the `1.0-stable` tag (not to be confused with the `1.0-dev` branch). That's usually what's behind similar issues.

**Comment by AnishDe12020** [comment]
> Hey there,
> 
> Please double-check, if you got the toolkit from the `1.0-stable` tag (not to be confused with the `1.0-dev` branch). That's usually what's behind similar issues.

Got the same error, I am using `1.0` (the default branch)

**Comment by elsaco** [comment]
It does build an ISO when checking out tag 1.0-stable.  Thank you!

**Comment by MateuszMalisz** [comment]
Glad we were able to resolve your issue. :)
