### ISSUE TITLE
unable to create ISO

### ISSUE THREAD

**Issue by raj07raj** [microsoft/CBL-Mariner#1194]
Hi Team,

Getting below error:

[root@localhost toolkit]# make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json
cd /media/CBL-Mariner/toolkit/tools/ && \
	go test -covermode=atomic -coverprofile=/media/CBL-Mariner/build/tools/internal.test_coverage ./...
go: golang.org/x/sys@v0.0.0-20200509044756-6aff5f38e54f: Get "https://goproxy.io/golang.org/x/sys/@v/v0.0.0-20200509044756-6aff5f38e54f.mod": x509: certificate signed by unknown authority
make: *** [/media/CBL-Mariner/build/tools/internal.test_coverage] Error 1

I am new to go lang. Please suggest ???

**Comment by tingyin-duan** [comment]
> Hi Team,
> 
> Getting below error:
> 
> [root@localhost toolkit]# make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json
> cd /media/CBL-Mariner/toolkit/tools/ &&
> go test -covermode=atomic -coverprofile=/media/CBL-Mariner/build/tools/internal.test_coverage ./...
> go: golang.org/x/sys@v0.0.0-20200509044756-6aff5f38e54f: Get "https://goproxy.io/golang.org/x/sys/@v/v0.0.0-20200509044756-6aff5f38e54f.mod": x509: certificate signed by unknown authority
> make: *** [/media/CBL-Mariner/build/tools/internal.test_coverage] Error 1
> 
> I am new to go lang. Please suggest ???

you may need type a command "go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/"  to set  GOPROXY properly.

**Comment by raj07raj** [comment]
**go env -w GOPROXY=http://mirrors.aliyun.com/goproxy/.**  Changed https to http fixed the issue. Thanks
