### ISSUE TITLE
Error when creating ISO even after retrying

### ISSUE THREAD

**Issue by AnishDe12020** [microsoft/CBL-Mariner#1221]
So I was creating the ISO with the `sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json` command and it errored out. I retried and I am receiving the same error

Error - 
![image](https://user-images.githubusercontent.com/63192115/127742460-d44a43bd-7f95-4408-ac87-d275c2399c1d.png)

Could anyone please help me diagnose the issue?

**Comment by ddstreetmicrosoft** [comment]
sorry for the lack of response; i'm closing this since it has been open so long, but if you are still having issues please reopen.
