### ISSUE TITLE
CBL-Mariner from the Microsoft Store (in the future)? Or alternatively, how to install it via wsl + the .iso mentioned on the blog from Juan?

### ISSUE THREAD

**Issue by rubyFeedback** [microsoft/CBL-Mariner#1222]
CBL-Mariner on the Microsoft Store?

Hey folks,

I am primarily a Linux user. On my desktop machine I have a customized
slackware variant, but I compile about 99% of software from source.
Anyway.

On my Win10 laptop I run WSL1 still (will eventually switch to WSL2
but you know how it goes ... once things are working fine, and 
everything is working quite nicely on WSL1, inertia kicks in), most
of the time ubuntu, but also SUSE Linux.

I'd like to test CBL-Mariner as well. This is less so about "which
unique features does CBL Mariner have"; I am aware that your target
audience is probably other folks, e. g. cloud/business people so
less "hobbyists". But my main rationale for wanting to try CBL-Mariner
is actually the thought that CBL-Mariner may be better "optimised"
for Win10 than Linux distributions per se. Perhaps not in WSL1 but
in WSL2 - no clue. And perhaps not right now, but in the future. So
I want to "anticipate" a little bit in the future.

Anyway. I took a look at the Microsoft Store, and while Ubuntu and
SUSE are available there, CBL-Mariner is not available.

Now there may be several reasons as to why. I assume one reason 
may be that you guys haven't everything "fully prepared" as-is,
and CBL-Mariner is still in flux. That's fine.

See also articles such as this:

https://www.zdnet.com/article/say-hi-to-microsofts-own-linux-cbl-mariner/

Which brought me to that blog entry:

https://blog.jreypo.io/2021/07/09/a-look-into-cbl-mariner-microsoft-internal-linux-distribution/

by Juan Manuel Rey. I had a look at the main README.md here, and also
the link to this entry:

https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/README.md

But I did not seem to see that blog, so perhaps some information is
not "gathered" in the main README or other documentation parts. But
this is an aside.

So my question is:

- Would it be possible to add CBL-Mariner, at the least the ".iso"
variant that Juan talks about, to the Microsoft Store?

Note: I don't mean that you guys have to provide a new .iso here
every week; but something sensible, such as 3-months releases or
even 6-months releases. My use case is really the very same I use
ubuntu on WSL1 too right now. I can adapt my workflow without 
having to modify it a lot; all my ruby commandline scripts work
fine (most work fine on plain windows anyway, but cmd.exe is a
bit more annoying to work with, and there are some platform 
differences still that require adjustments to my scripts every
now and then).

Of course I do not know whether that conflicts with any other goal
or policies, or whether there are tier use cases that require 
financial investments or not, but I am really talking about the
"hobbyist" use case primarily, not the business side. Just like
the blog entry shows with the .iso that is created. (I assume
it may even be possible to just install such an .iso and have
it work similar to how ubuntu or SUSE works, but I also lack
information, which is why I created this issue. Being able to
install from the Microsoft Store directly would be most 
convenient, but if this is not possible for any reason, then
perhaps a document that showcases the initial step-by-step 
commands for getting CBL-Mariner to work.)

Please feel free to close this issue at any moment in time;
and if this is planned, but not yet working anyway, but may
work in the future, then please feel free to close the issue
as well. Thanks for reading.

**Comment by christopherco** [comment]
Mariner does not officially support WSL at this time. We will continue to re-evaluate this going forward.
