### ISSUE TITLE
Issue with kernel-headers rpm download

### ISSUE THREAD

**Issue by ajoybharath** [microsoft/CBL-Mariner#1250]
Encountered the issue of downloading kernel-headers-5.10.52.1-3.cm1.noarch.rpm. While digging in to the URL https://packages.microsoft.com/cbl-mariner/1.0/prod/base/x86_64/rpms/   I could only see kernel-headers-5.4.51-2.cm1.noarch.rpm. The build is going on in an Ubuntu 18.04 system

Snippet from the error while executing make iso
Downloading toolchain RPM: kernel-headers-5.10.52.1-3.cm1.noarch.rpm

ERROR: Failed to download toolchain package: kernel-headers-5.10.52.1-3.cm1.noarch.rpm.
ERROR: Last 20 lines from log '/home/ubuntu/CBL-Mariner/build/logs/toolchain/downloads/kernel-headers-5.10.52.1-3.cm1.noarch.rpm.log':

	Downloading toolchain RPM: kernel-headers-5.10.52.1-3.cm1.noarch.rpm
	--2021-08-08 16:59:43--  https://packages.microsoft.com/cbl-mariner/1.0/prod/base/x86_64/rpms/kernel-headers-5.10.52.1-3.cm1.noarch.rpm
	Resolving packages.microsoft.com (packages.microsoft.com)... 52.230.121.169
	Connecting to packages.microsoft.com (packages.microsoft.com)|52.230.121.169|:443... connected.
	HTTP request sent, awaiting response... 404 Not Found
	2021-08-08 16:59:43 ERROR 404: Not Found.
	
	--2021-08-08 16:59:43--  https://packages.microsoft.com/cbl-mariner/1.0/prod/update/x86_64/rpms/kernel-headers-5.10.52.1-3.cm1.noarch.rpm
	Resolving packages.microsoft.com (packages.microsoft.com)... 52.163.211.218
	Connecting to packages.microsoft.com (packages.microsoft.com)|52.163.211.218|:443... connected.
	HTTP request sent, awaiting response... 404 Not Found
	2021-08-08 16:59:43 ERROR 404: Not Found.

**Comment by mfrw** [comment]
@ajoybharath what branch/tag are you building specifically ?

**Comment by ajoybharath** [comment]
> @ajoybharath what branch/tag are you building specifically ?

1.0

**Comment by mfrw** [comment]
Can you please try to build tag `1.0.20210720-1.0` for now.
You could try:

```bash
git checkout -f 1.0.20210720-1.0
git clean -f
sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n  CONFIG_FILE=./imageconfigs/core-efi.json SOURCE_URL="https://cblmarinerstorage.blob.core.windows.net/sources/core"
```

**Comment by ajoybharath** [comment]
Thank you, let me try that

**Comment by PawelWMS** [comment]
In general, please always double-check the [building prerequisites](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/quick_start/quickstart.md) and run the toolkit from the `1.0-stable` tag to avoid building issues. Any other branch or tag have high changes of failure.

**Comment by mfrw** [comment]
@ajoybharath closing the issue, please reopen if you face issues :)
