### ISSUE TITLE
Add a GitHub check for documentation formatting

### ISSUE THREAD

**Issue by PawelWMS** [microsoft/CBL-Mariner#126]
It seems that despite our best efforts our .md files don't follow any single rule when it comes to formatting. It would be ideal to add an automated check for that for each documentation PR. My first suggestion is to follow the rules mentioned [here](https://github.com/DavidAnson/markdownlint/blob/v0.20.4/doc/Rules.md).

**Comment by dmcilvaney** [comment]
We have a similar check for the Go files.
- A Github Action is run which checks out the current PR/commit (https://github.com/microsoft/CBL-Mariner/blob/83de3e225d554f749ea3a56c700e9c644afbe999/.github/workflows/go-test-coverage.yml#L25)
- We manually run the `go fmt ./...` command on our Go sources via the `go-fmt-all` Makefile target
- Run `git diff` to see if the auto format changed anything

If there is a similar command we can use the same pattern, or failing that just scrape the output of the tool for errors.

**Comment by WSLUser** [comment]
I suggest using https://github.com/github/super-linter/. Just create the file(s) and you'll having markdown, yaml, etc. linter checks done automatically that are reviewable in the build steps of the PR.

**Comment by WSLUser** [comment]
I also suggest https://github.com/jsoref/spelling for spelling issues.

**Comment by dmcilvaney** [comment]
I had a run through super-linter, its quite a neat system.

Unfortunately many of the files from upstream packages don't pass the checks, so there are a huge number of errors which we can't reasonably fix. It also doesn't like that our go code is not found in the root directory and my attempts to make it happy failed.

That said, I'm going to look at setting up some of the included linters manually as stand alone checks (The go linter especially is quite powerful).

**Comment by WSLUser** [comment]
You can ignore the linter checks. Yes you'll have a red X instead of a nice green check but PRs are still mergeable. Don't waste time on it just to get a green check. Also if upstream packages have bunch of linter errors, I'd suggest filing issues for them to get fixed.

**Comment by jslobodzian** [comment]
SPEC file linting is part of the automated checks.  It is recommended to update pre-existing specs as they are touched.  New specs should adhere to the spec linter formatting.
