### ISSUE TITLE
BPF Type Format file is missing

### ISSUE THREAD

**Issue by mjsabby** [microsoft/CBL-Mariner#128]
Most distributions have `/sys/kernel/btf/vmlinux` which is where the [BPF Type Format](https://www.kernel.org/doc/html/latest/bpf/btf.html) information for the kernel is stored.

This is missing in Mariner.

If this is deliberate, we should document it and if not fixing it would be great.

**Comment by mjsabby** [comment]
Any update on this?

**Comment by ddstreetmicrosoft** [comment]
This `/sys/kernel/btf/vmlinux` file appears to be present in the latest mariner 2, so closing this.
