### ISSUE TITLE
Unattended Installation Fails with 1.0-stable

### ISSUE THREAD

**Issue by aaronamorim** [microsoft/CBL-Mariner#1310]
Building an unattended ISO installation with the 1.0 branch fails during installation.

Build process:
1) A copy of image config full.json was created and modified to only contain the "CBL-Mariner Full" SystemConfig.  New json file name full-auto.json
2) ISO was built using the following command line (note tools had previously been build when creating an attended ISO): sudo make iso REBUILD_TOOLS=n REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full-auto.json UNATTENDED_INSTALLER=y
3) Build was successful - log attached

Run time environment:
Hyper-V Server 2019
VM Configuration (Gen 2):
4 vCPUs
8GB RAM
1 vhdx (127GB)
2 vNICs
UEFI settings set to secure boot/MS UEFI Certificate Authority

I've attached the console output (as much as I can get).  If other logs are required please advise (including if possible how to extract them from the run time image inside the VM)

Side Note: I see nothing in the document of how to customize the unattended installation (i.e. default hostname, user account, partition structure, etc).  Is this supported and/or am I just missing something blindingly obvious :( ?

Attached
[buildlog.log](https://github.com/microsoft/CBL-Mariner/files/7021592/buildlog.log)
![InstallOutput](https://user-images.githubusercontent.com/42279083/130237901-a86e82c7-304f-4635-a32d-0539a167efd3.jpg)

**Comment by elsaco** [comment]
The config file you specified might not have enough info for unattended installation.

Your config file is missing storage definition, something like:

>     "Disks": [
>         {
>             "PartitionTableType": "gpt",
>             "MaxSize": 2048,
>             "Artifacts": [
>                 {
>                     "Name": "core",
>                     "Type": "vhd"
>                 }
>             ],
>             "Partitions": [
>                 {
>                     "ID": "boot",
>                     "Flags": [
>                         "grub"
>                     ],
>                     "Start": 1,
>                     "End": 9,
>                     "FsType": "fat32"
>                 },
>                 {
>                     "ID": "rootfs",
>                     "Start": 9,
>                     "End": 0,
>                     "FsType": "ext4"
>                 }
>             ]
>         }
>     ],

And mount points. See "imageconfigs/core-legacy.json" for examples.

**Comment by aaronamorim** [comment]
Thank you very much - I scanned through a number of image configs (especially in the demo project) for pointed but clearly not this one.  I figured it must be something like this.  I'm going to do a pull request for build documentation to add something for this as currently it simply says "use UNATTENDED_INSTALLER=y and ensure only a single SystemConfig".  Alternatively, is the format of the imageconfig json files governed by a document somewhere that perhaps I missed?

**Comment by aaronamorim** [comment]
Sorry for the delay in replying - I've been OOO.  Here's a sample file of how I made it work.  The principal thing I had to do was add the "Disks" section of the configuration as well as the PartitionSettings and Users sections of SystemConfigs.

[auto.txt](https://github.com/microsoft/CBL-Mariner/files/7587808/auto.txt)
