### ISSUE TITLE
Mariner porting to arm64 platform

### ISSUE THREAD

**Issue by Stanley-Yan-gituser** [microsoft/CBL-Mariner#133]
I am trying to port mariner to imx8(aarch64) custom board, but encounter some problems.

Build environment as following:
_mariner github tag:  **1.0-stable**
build machine:  **x86_64**
target platform:  **imx8(aarch64) custom board, bootloader is uboot which is support UEFI binary**_

first, I follow quick start steps(like the following commands) to build mariner images.
	

- sudo make toolchain REBUILD_TOOLS=y REBUILD_TOOLCHAIN=y DOWNLOAD_SRPMS=y

	

- sudo make build-packages -j$(nproc) CONFIG_FILE= TOOLCHAIN_ARCHIVE=toolchain_built_rpms_all.tar.gz DOWNLOAD_SRPMS=y REBUILD_TOOLS=y REBUILD_TOOLCHAIN=n REBUILD_PACKAGES=y PACKAGE_IGNORE_LIST="openjdk8 openjdk8_aarch64 shim-unsigned-aarch64"

	

- sudo make make-raw-image CONFIG_FILE=./imageconfigs/core-efi.json TOOLCHAIN_ARCHIVE=toolchain_built_rpms_all.tar.gz REBUILD_TOOLCHAIN=n REBUILD_PACKAGES=n REBUILD_TOOLS=y REPO_LIST=

After completed above steps, I got image files in **"./build/imagegen/core-efi/imager_output/" or "../out/images/full"** path.
But I found that the **grub64.efi ,vmlinux** and **rootfs files** in  image file is x86 elf format, these images file can't run on imx8 platform.
So do i need an aarch64 host machine to build mariner arm64 images instead of x86 host? or there are other way to run the mariner in imx8 platform.
Could someone give me a suggestion for this problem?
Thanks.

**Comment by PawelWMS** [comment]
Hi there, Stanley! Mariner tooling currently requires the build machine to be the same architecture as the target one as far as I am aware, so you would need to run on an ARM64 machine in this case.

@christopherco: can you provide any additional help here? I believe you have a lot more experience in building images for ARM64 machines.

**Comment by WSLUser** [comment]
Is there any way Visual Studio could help with this utilizing WSL2?

**Comment by JadeCoding** [comment]
> I am trying to port mariner to imx8(aarch64) custom board, but encounter some problems.
> 
> Build environment as following:
> _mariner github tag: **1.0-stable** build machine: **x86_64** target platform: **imx8(aarch64) custom board, bootloader is uboot which is support UEFI binary**_
> 
> first, I follow quick start steps(like the following commands) to build mariner images.
> 
> * sudo make toolchain REBUILD_TOOLS=y REBUILD_TOOLCHAIN=y DOWNLOAD_SRPMS=y
> * sudo make build-packages -j$(nproc) CONFIG_FILE= TOOLCHAIN_ARCHIVE=toolchain_built_rpms_all.tar.gz DOWNLOAD_SRPMS=y REBUILD_TOOLS=y REBUILD_TOOLCHAIN=n REBUILD_PACKAGES=y PACKAGE_IGNORE_LIST="openjdk8 openjdk8_aarch64 shim-unsigned-aarch64"
> * sudo make make-raw-image CONFIG_FILE=./imageconfigs/core-efi.json TOOLCHAIN_ARCHIVE=toolchain_built_rpms_all.tar.gz REBUILD_TOOLCHAIN=n REBUILD_PACKAGES=n REBUILD_TOOLS=y REPO_LIST=
> 
> After completed above steps, I got image files in **"./build/imagegen/core-efi/imager_output/" or "../out/images/full"** path.
> But I found that the **grub64.efi ,vmlinux** and **rootfs files** in image file is x86 elf format, these images file can't run on imx8 platform.
> So do i need an aarch64 host machine to build mariner arm64 images instead of x86 host? or there are other way to run the mariner in imx8 platform.
> Could someone give me a suggestion for this problem?
> Thanks.

It requires arm64 machine as host, I used Raspberry Pi 4 built the toolchain.

**Comment by Stanley-Yan-gituser** [comment]
> Hi there, Stanley!
> 
> Mariner tooling currently requires the build machine to be the same architecture as the target one as far as I am aware, so you would need to run on an ARM64 machine in this case.
> 
> @christopherco: can you provide any additional help here? I believe you have a lot more experience in building images for ARM64 machines.

Thanks for your information, I am trying to build mariner images on arm64 virtual machine.
In the future, if mariner can use arm cross-compilers to build images instead of Physical machines, it may speed up the compiler time.

**Comment by jslobodzian** [comment]
Mariner does not presently support cross compile.  Please build on natively on ARM64 systems.
