### ISSUE TITLE
Use Clear Linux optimized packages

### ISSUE THREAD

**Issue by WSLUser** [microsoft/CBL-Mariner#137]
From what I can gather, it appears that packages are taken either from upstream or Fedora. Clear Linux provides optimized rpm packages which are built with autospec (a tool I think should be the default for rpm generation). The need for using the bundles isn't there and they do have a repo that can be used with dnf directly. So I propose basically repackaging those packages for Mariner using the same optimizations.

**Comment by sr229** [comment]
I don't see the benefit of using Clear Linux packages since using the Fedora packages is quite okay. Fedora benefits on a more broader ecosystem, CL has optimized packages with lesser packages.

**Comment by WSLUser** [comment]
The way CBL_Mariner imports packages would allow them to use both (they take the same approach as Clear Linux). So they could use Clear Linux optimized packages where available and Fedora packages where it's not. Alternatively they could take the optimization mechanism and use it for more Fedora packages but that would require them to adopt mixer, which I'm not sure if they should do or not. The original request is easier to implement as they can simply point to the rpm packages in the Clear Linux package mirror.

**Comment by sr229** [comment]
> The way CBL-Mariner imports packages would allow them to use both (they take the same approach as Clear Linux). So they could use Clear Linux optimized packages where available and Fedora packages where it's not. Alternatively they could take the optimization mechanism and use it for more Fedora packages but that would require them to adopt mixer, which I'm not sure if they should do or not. The original request is easier to implement as they can simply point to the rpm packages in the Clear Linux package mirror.

That's actually a good take. I would appreciate RPMs with the CL optimizations honestly.
