### ISSUE TITLE
Duplicate files in grpc-devel

### ISSUE THREAD

**Issue by tofay** [microsoft/CBL-Mariner#1518]
Some files in grpc-devel are shown by RPM as appearing twice

```
root [ / ]# tdnf install grpc-devel
...
root [ / ]# rpm -qf /usr/lib64/libre2.so
grpc-devel-1.35.0-4.cm1.x86_64
grpc-devel-1.35.0-4.cm1.x86_64
root [ / ]#
```

The RPM contains /usr/lib/libre2.so and /usr/lib64/libre2.so, which have the same canonicalized filepath. I think that's because of this section of the [grpc spec](https://github.com/microsoft/CBL-Mariner/blob/1.0/SPECS/grpc/grpc.spec#L82) which :
```
%{_libdir}/*.so
%{_lib64dir}/*.so
```

Only impact this had is that it caused some downstream tooling to fail (as they expect any file in an RPM based OS to be owned by at most one package).

**Comment by oliviacrain** [comment]
Closing this issue- I've inspected the `grpc-devel` packages for our 1.0 and 2.0 branches, and the file conflict is no longer present.
