### ISSUE TITLE
Unable to Hyrdrate File

### ISSUE THREAD

**Issue by danrald** [microsoft/CBL-Mariner#1525]
I build the image on ubuntu and nothing was dropped into the images/full directory.

I got an error though:
unable to hydrate file: GSL-2.0.0.tar.gz

I'm bran new to linux and was interested in CBL, so I created a hyper-v ubuntu got all the git code and did the builds to create the iso.
I don't see a file named GSL-2.0.0.tar.gz in the repo though.

**Comment by PawelWMS** [comment]
No response for a few days, closing issue.
