### ISSUE TITLE
librsvg2 is not found in any Mariner repository

### ISSUE THREAD

**Issue by seflerZ** [microsoft/CBL-Mariner#1599]
WSLg now uses librsvg2 for parsing SVG icon files. However the building environment using CBL-Mariner doesn't have librsvg2 in repositories. Need to add that.

https://github.com/microsoft/wslg/issues/70

**Comment by hideyukn88** [comment]
@seflerZ, we are working on it.

**Comment by seflerZ** [comment]
I've found the lib has been added. Closing the issue
![image](https://user-images.githubusercontent.com/2093588/162377592-b5e36d9f-f420-4bb4-8c2e-b37dfb56ffd4.png)
