### ISSUE TITLE
Running 32 bit Binary fails with an exec error

### ISSUE THREAD

**Issue by AESNooper** [microsoft/CBL-Mariner#1620]
Hi,
I've tried running a 64 bit and 32 bit (386) binary. Running the 64 bit binary is fine. Upon running the 32 bit (386) binary I get the following error:

![32biterror](https://user-images.githubusercontent.com/29008723/140289895-4a50485d-df00-4a3b-8b7f-c35124f6c431.png)

I have skimmed through the official packages but couldn't find anything useful to run 32 bit binaries.
Is there anything I can do to run 32 bit binaries on CBL-Mariner?

**Comment by PawelWMS** [comment]
Hi there,

CBL-Mariner currently is intended only for AMD64 and ARM64 machines without support for 32-bit binaries.

**Comment by AESNooper** [comment]
Hi,

thanks for the fast reply! 
Unfortunate to hear that it's not supported.

Best regards,
AESNooper
