### ISSUE TITLE
Graphical installer omits LVM LV creation (1.0.20211104)

### ISSUE THREAD

**Issue by hawko2600** [microsoft/CBL-Mariner#1636]
In the Partition configuration, to do a standard LVM layout you go into "Manual" mode and can create a LVM PV. Unfortunately there's then no option to create a LV inside the PV, and the installer cannot continue as your only options are to abort the installation or to step back out of the partitioning section since there's not yet a root filesystem available to install to.

As an aside, there's also no support for the standard xfs filesystem.

I imagine both omissions are due to CBL-Mariner being targetted at ephemeral containers and so persistent storage isn't a concern for the usual use case.

For system security and availability reasons, it's standard practice to break the filesystem into multiple partitions but due to x86 BIOS limitations, you can't have enough (max 4) without using LVM, with two being taken for UEFI and boot. Consider std FHS layout:

/ <-- read-only - binaries/libs required for system bootstrap (init stage 1/2)
/boot <-- read-only
/boot/efi <-- read-only (required for UEFI)
/usr <-- read-only binaries/libs required for system applications (init stage 3)
/home <-- read/write nodev nosuid
/var <-- read-write,nodev,nosuid
/var/tmp <-- read-write, nosuid
/var/log <-- read-write, nodev, nosuid
swap
(/dev, /tmp, /sys, /proc are ephemeral and handled by their respective devfs, tmpfs etc at runtime)

This is a generic template with the only real variables being the size given to each partition, and what filesystem is appropriate for the use case (IoT v mobile v metal v virtual). Unfortunately a form of laziness/ineptitude has leaked in where predominately Windows people would just think root filesystem = C: and therefore lets just have one big / drive- this would fit into the 4 standard partition limit, but of course leave the system open to a lot of denial of service and other security issues trivially avoided by configuring Windows systems like Windows and Linux systems like Linux.

**Comment by jholt0147** [comment]
I have never in my life encountered any Linux distro that mounts /usr let alone / as read-only

**Comment by christopherco** [comment]
Thank you for your proposal. However this is not a supported configuration for Mariner at this time.
