### ISSUE TITLE
Grahpical desktop ?

### ISSUE THREAD

**Issue by PREKNOWLEDGEWEB** [microsoft/CBL-Mariner#1662]
any GUI desktop for it ? since it can run xfce4

**Comment by AVI757** [comment]
its possible, but requires you to download a LOT of dependencies. Not really worth the time and effort imo

**Comment by ddstreetmicrosoft** [comment]
no, there is no graphical desktop available currently.

**Comment by lewisdonofrio** [comment]
https://www.youtube.com/watch?v=qvtYyLYRKhI
