### ISSUE TITLE
Adding AD integration support (sssd/realmd)

### ISSUE THREAD

**Issue by aaronamorim** [microsoft/CBL-Mariner#1706]
I'm raising this issue to see if there's any intention of adding AD integration support to CBL-Mariner.  Our use case for CBL-Mariner is to form a small farm for the purposes of running docker container in an otherwise Windows environment.  Being able to use AD IAM functions for CBL-Mariner based servers would be extremely helpful.

I'm also currently in the process of adding sssd/realmd myself using Fedora SPEC files as a starting point.  I'd have no issues submitting my work as a pull request once it's done (if this sort of functionality is something the core team is interested in) but to that end: are there any guidelines in terms of testing, structure, or format for pull requests?

**Comment by christopherco** [comment]
No plans to supply AD integration support natively in today's releases. We will re-evaluate this in future major releases.
