### ISSUE TITLE
Quickstart guide build broken in #1804 (missing binutils package version in repo)

### ISSUE THREAD

**Issue by neg2led** [microsoft/CBL-Mariner#1834]
Hi all :)

#1804 has broken the [quickstart guide](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/quick_start/quickstart.md) build:

```
❯ sudo make image REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/core-efi-virt.json
Downloading toolchain RPM: binutils-2.36.1-2.cm1.x86_64.rpm
\nERROR: Failed to download toolchain package: binutils-2.36.1-2.cm1.x86_64.rpm.
ERROR: Last 20 lines from log '~/software/k8stuff/cbl-mariner/build/logs/toolchain/downloads/binutils-2.36.1-2.cm1.x86_64.rpm.log':\n
        Downloading toolchain RPM: binutils-2.36.1-2.cm1.x86_64.rpm
        --2022-01-04 14:09:14--  https://packages.microsoft.com/cbl-mariner/1.0/prod/base/x86_64/rpms/binutils-2.36.1-2.cm1.x86_64.rpm
        Resolving packages.microsoft.com (packages.microsoft.com)... 52.230.121.169
        Connecting to packages.microsoft.com (packages.microsoft.com)|52.230.121.169|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2022-01-04 14:09:15 ERROR 404: Not Found.

        --2022-01-04 14:09:15--  https://packages.microsoft.com/cbl-mariner/1.0/prod/update/x86_64/rpms/binutils-2.36.1-2.cm1.x86_64.rpm
        Resolving packages.microsoft.com (packages.microsoft.com)... 52.230.121.169
        Connecting to packages.microsoft.com (packages.microsoft.com)|52.230.121.169|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2022-01-04 14:09:15 ERROR 404: Not Found.

\nToolchain download failed. See above errors for more details.
make: *** [~/software/k8stuff/cbl-mariner/toolkit/scripts/toolchain.mk:200: ~/software/k8stuff/cbl-mariner/build/rpm_cache/cache/x86_64/binutils-2.36.1-2.cm1.x86_64.rpm] Error 1
```

Build system is unable to find the `binutils`, `binutils-devel`, `mariner-release` RPMs in the repo at https://packages.microsoft.com/cbl-mariner/1.0/prod/base/x86_64/rpms/ and as a result it fails.

I did find the relevant RPMs over at https://packages.microsoft.com/yumrepos/cbl-mariner-1.0-preview-update-x86_64-rpms/ so I manually downloaded them into the appropriate `rpm_cache` directories to work around this myself, but it seems like someone needs to move a few files around on the package repo server 😜

**Comment by PawelWMS** [comment]
Hi @neg2led,

This shouldn't be happening. Could you double-check, if you're using the `1.0-stable` tag and not the `1.0-dev` branch? The #1804 change has not been released to the RPM repository, yet and shouldn't influence any builds. Please keep in mind that building from the `1.0-dev` branch will usually fail with similar messages as the ones you're seeing.

**Comment by neg2led** [comment]
Hi @PawelWMS :) you're right, I attempted to use v2.0 when it's clearly not _quite_ ready/available just yet. Worked that out about an hour after I opened this... my bad, sorry for the trouble (and the slow response)!
