### ISSUE TITLE
Unable to add new package 'libdrm'

### ISSUE THREAD

**Issue by rradjabi** [microsoft/CBL-Mariner#184]
I'm trying to extend CBL-Mariner to include libdrm in the installation. 

For a baseline, I am using 1.0-stable, and without any modifications to the repository, I am able to successfully build an ISO image, and install/run this OS using the following command sequence :
## Get the source code
`git clone https://github.com/microsoft/CBL-Mariner.git
cd CBL-Mariner/toolkit`

## Checkout the desired release branch. The 1.0-stable tag tracks the most recent successful `release of the 1.0 branch.
git checkout 1.0-stable`

## Build the Go tools
`sudo make go-tools REBUILD_TOOLS=y`

## Get the package sources
`sudo make input-srpms DOWNLOAD_SRPMS=y`

## Build an ISO version of ./imageconfigs/core-efi.json entirely from downloaded, pre-built packages
`sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n`

Now I would like to build a new ISO that allows me to install **libdrm**, so I've attempted to follow instructions for adding a SPEC file CBL-Mariner/SPECS/libdrm/libdrm.spec. It is unclear to me what additional steps are necessary to build Mariner so that libdrm is supported. I am referencing libdrm packages located at https://dri.freedesktop.org/libdrm/. I have attempted a variety of commands from the documentation in order to build this additional package, but have not been successful.

Any suggestions on how to proceed would be appreciated.

**Comment by PawelWMS** [comment]
Hi @rradjabi! Could you share the commands and errors you're getting when building the ISO with the new package?

Most instructions should be available [here](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/building/building.md#packages) but I see that this section could use some expansion - thank you for pointing this out.

**Comment by thcrain-msft** [comment]
Hi @rradjabi! Glad you were able to build an image on 1.0-stable- always love to hear that our tooling works well for those outside the Mariner team 😄 

It sounds like you're trying to add a package to an ISO image- it's a bit hard to suggest how to proceed without knowing what exactly you've read/tried, but (in addition to Pawel's suggestion) I would suggest reading the following:

- [Documentation on the image generation process](https://github.com/microsoft/CBL-Mariner/blob/1.0-dev/toolkit/docs/how_it_works/4_image_generation.md)
- [Documentation on the image configuration file format](https://github.com/microsoft/CBL-Mariner/blob/1.0-dev/toolkit/docs/formats/imageconfig.md)

**Comment by rradjabi** [comment]
@PawelWMS , @thcrain-msft ,

Happy to share an example of what I've done and the errors that returned. I've tried many computations, so I wasn't sure which to share, but here is one example.

`
  > git clone https://github.com/microsoft/CBL-Mariner.git
  > cd CBL-Mariner/toolkit
  >  git checkout 1.0-stable
  >  sudo make go-tools REBUILD_TOOLS=y
  >  sudo make input-srpms DOWNLOAD_SRPMS=y
  >  sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n
`

Now I want to rebuild and add the SPEC file for libdrm, so I’ve created the file ‘CBL-Mariner/SPECS/libdrm/libdrm.spec’ with the following spec file contents listed below. 

The build error I get is: 
`
        spec_file=${spec} && \
        srpm_file=$(rpmspec -q ${spec_file} --srpm --define='with_check 1' --define='dist .cm1' --queryformat %{NAME}-%{VERSION}-%{RELEASE}.src.rpm) && \
        wget https://packages.microsoft.com/cbl-mariner/1.0/prod/base/srpms/${srpm_file} \
                -O /home/user/Ryan/stable/CBL-Mariner/toolkit/../build/INTERMEDIATE_SRPMS/${srpm_file} \
            --no-verbose \
             \
             \
            && \
        touch /home/user/Ryan/stable/CBL-Mariner/toolkit/../build/INTERMEDIATE_SRPMS/${srpm_file}  || \
                { echo "Failed to download ${srpm_file}" ; exit 1 ; } ; \
done || { echo "Loop in /home/user/Ryan/stable/CBL-Mariner/toolkit/../build/make_status/build_srpms.flag failed" ; exit 1 ; } ; \
touch /home/user/Ryan/stable/CBL-Mariner/toolkit/../build/make_status/build_srpms.flag
Failed to download libdrm-2.4.100-0.src.rpm
/home/user/Ryan/stable/CBL-Mariner/toolkit/scripts/srpm_pack.mk:42: recipe for target '/home/user/Ryan/stable/CBL-Mariner/toolkit/../build/make_status/build_srpms.flag' failed
`

## libdrm.spec
```
#
# spec file for package libdrm
#
# Copyright (c) 2013 SUSE LINUX Products GmbH, Nuernberg, Germany.
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via http://bugs.opensuse.org/
#


Name:           libdrm
Url:            http://dri.freedesktop.org/
Version:        2.4.100
Release:        0
Provides:       libdrm23 = %{version}
Obsoletes:      libdrm23 < %{version}
# bug437293
%ifarch ppc64
Obsoletes:      libdrm-64bit < %{version}
Provides:       libdrm-64bit = %{version}
%endif
#
Summary:        Userspace Interface for Kernel DRM Services
License:        MIT
Group:          System/Libraries

#Git-Clone:     git://anongit.freedesktop.org/git/mesa/drm
#Git-Web:       http://cgit.freedesktop.org/mesa/drm/
Source:         http://dri.freedesktop.org/libdrm/%{name}-%{version}.tar.bz2
#Source:         https://kojipkgs.fedoraproject.org//packages/libdrm/2.4.102/1.fc33/x86_64/libdrm-2.4.102-1.fc33.x86_64.rpm
Source2:        baselibs.conf
# PATCH-FIX-UPSTREAM libdrm-implicit-defs.diff fdo#48599 -- Fix compiler warnings in tests/radeon/radeon_ttm.c
Patch1:         libdrm-implicit-defs.diff
Patch2:         u_Fix-compilation-on-systems-that-don-t-provide-O_CLOE.patch

BuildRoot:      %{_tmppath}/%{name}-%{version}-build
BuildRequires:  autoconf >= 2.63
BuildRequires:  automake >= 1.10
BuildRequires:  libtool >= 2.2
BuildRequires:  pkgconfig
BuildRequires:  pkgconfig(pciaccess) >= 0.10
BuildRequires:  pkgconfig(pthread-stubs)
%ifnarch armv5el armv5tel aarch64
BuildRequires:  pkgconfig(valgrind)
%endif

%description
The package contains the userspace interface to the kernel DRM
services.

%package tools
Summary:        Diagnostic utilities for DRI and DRM
Group:          System/Base
# O/P added in 12.2
Obsoletes:      libdrm < %version-%release
Provides:       libdrm = %version-%release

%description tools
(Upstream has not provided a description)

%package devel
Summary:        Libraries, includes and more to develop libdrm applications
Group:          Development/Libraries/X11
Requires:       libdrm2 = %version
Requires:       libdrm_nouveau2 = %version
Requires:       libdrm_radeon1 = %version
%ifarch %arm
Requires:       libdrm_omap1 = %version
%endif
%ifarch %ix86 x86_64
Requires:       libdrm_intel1 = %version
%endif
# bug437293
%ifarch ppc64
Obsoletes:      libdrm-devel-64bit < %{version}
Provides:       libdrm-devel-64bit = %{version}
%endif

%description devel
libdrm is a library for accessing the Direct Rendering Manager on
Linux, BSD and other operating systes that support the ioctl
interface, and for chipsets with DRM memory manager, support for
tracking relocations and buffers. libdrm is a low-level library,
typically used by graphics drivers such as the Mesa DRI and X
drivers.

This package contains the development headers for the library found
in libdrm2.

%package -n libdrm2
Summary:        Userspace Interface for Kernel DRM Services
Group:          System/Libraries

%description -n libdrm2
libdrm is a library for accessing the Direct Rendering Manager on
Linux, BSD and other operating systes that support the ioctl
interface, and for chipsets with DRM memory manager, support for
tracking relocations and buffers. libdrm is a low-level library,
typically used by graphics drivers such as the Mesa DRI and X
drivers.

%package -n libdrm_intel1
Summary:        Userspace interface for Kernel DRM services for Intel chips
Group:          System/Libraries

%description -n libdrm_intel1
(Upstream has not provided a description)

%package -n libdrm_nouveau2
Summary:        Userspace interface for Kernel DRM services for NVIDIA chips
Group:          System/Libraries

%description -n libdrm_nouveau2
(Upstream has not provided a description)

%package -n libdrm_radeon1
Summary:        Userspace interface for Kernel DRM services for AMD Radeon chips
Group:          System/Libraries

%description -n libdrm_radeon1
(Upstream has not provided a description)

%package -n libkms-devel
Summary:        Development files for the KMS MM abstraction library
Group:          Development/Libraries/C and C++
Requires:       libkms1 = %version

%description -n libkms-devel
This package contains the development headers for the library found
in libkms1.

%package -n libkms1
Summary:        Userspace interface to kernel DRM buffer management
Group:          System/Libraries

%description -n libkms1
The KMS Memory Management abstraction library.

%ifarch %arm
%package -n libdrm_omap1
Summary:        Userspace interface to kernel DRM services for omap chips
Group:          System/Libraries

%description -n libdrm_omap1
(Upstream has not provided a description)
%endif

%prep
%setup -q
%patch1 -p1
%patch2 -p1

%build
export CFLAGS="$RPM_OPT_FLAGS -fno-strict-aliasing"
autoreconf -fi
%configure --with-pic \
%ifarch %arm
           --enable-omap-experimental-api \
%endif
           --enable-udev

make %{?_smp_mflags}
make %{?_smp_mflags} -C tests dristat drmstat

%check
make %{?_smp_mflags} -C tests check-am


%install
make install DESTDIR=$RPM_BUILD_ROOT
make -C tests/modeprint install DESTDIR=$RPM_BUILD_ROOT
make -C tests/modetest install DESTDIR=$RPM_BUILD_ROOT
rm -f "%buildroot/%_libdir"/*.la
%{__mkdir} -p $RPM_BUILD_ROOT/usr/bin
%{__install}  \
    tests/.libs/dristat \
    tests/.libs/drmstat \
    tests/modeprint/.libs/modeprint \
    tests/modetest/.libs/modetest $RPM_BUILD_ROOT/usr/bin

%post   -n libdrm2 -p /sbin/ldconfig

%postun -n libdrm2 -p /sbin/ldconfig

%post   -n libdrm_intel1 -p /sbin/ldconfig

%postun -n libdrm_intel1 -p /sbin/ldconfig

%post   -n libdrm_nouveau2 -p /sbin/ldconfig

%postun -n libdrm_nouveau2 -p /sbin/ldconfig

%post   -n libdrm_radeon1 -p /sbin/ldconfig

%postun -n libdrm_radeon1 -p /sbin/ldconfig

%post   -n libkms1 -p /sbin/ldconfig

%postun -n libkms1 -p /sbin/ldconfig

%ifarch %arm
%post   -n libdrm_omap1 -p /sbin/ldconfig

%postun -n libdrm_omap1 -p /sbin/ldconfig
%endif

%files tools
%defattr(-,root,root)
%_bindir/dristat
%_bindir/drmstat
%_bindir/modeprint
%_bindir/modetest


%files devel
%defattr(-,root,root)
%_includedir/libdrm
%ifarch %arm
%_includedir/omap
%endif
%_includedir/xf86drm.h
%_includedir/xf86drmMode.h
%_libdir/libdrm*.so
%_libdir/pkgconfig/libdrm*.pc
#%_mandir/man3/drm*

%files -n libdrm2
%defattr(-,root,root)
%_libdir/libdrm.so.2*

%ifarch %ix86 x86_64

%files -n libdrm_intel1
%defattr(-,root,root)
%_libdir/libdrm_intel.so.1*
%endif

%files -n libdrm_nouveau2
%defattr(-,root,root)
%_libdir/libdrm_nouveau.so.2*

%files -n libdrm_radeon1
%defattr(-,root,root)
%_libdir/libdrm_radeon.so.1*

%files -n libkms1
%defattr(-,root,root)
%_libdir/libkms.so.1*

%files -n libkms-devel
%defattr(-,root,root)
%_includedir/libkms
%_libdir/libkms.so
%_libdir/pkgconfig/libkms.pc

%ifarch %arm
%files -n libdrm_omap1
%defattr(-,root,root)
%_libdir/libdrm_omap.so.1*
%endif

%changelog

```

**Comment by dmcilvaney** [comment]
The culprit here is `DOWNLOAD_SRPMS=y`. Since its not practical to check in the source code for every package, and we want to have a reliable source to pull them from, we host them internally on a 'source server' (See documentation on `SOURCE_URL=`).  We make the sources available to the public via Source RPMs (SRPMS) which package both the spec files and their associated sources together.

The catch here: `DOWNLOAD_SRPMS=y` is an all or nothing flag, once it is on the build system looks exclusively to the package server for all its source and spec files (ignoring your new libdrm package). It knows you want a libdrm package, but can't find the SRPM on the server, so fails.

## Fix:
Assuming you don't want to setup your own source server, and if you don't mind using pre-built packages:

Delete every package out of ./SPECS *except* the ones you have modified, then disable `DOWNLOAD_SRPMS`. By default the build system will reach out to the package server to find any missing packages during both package build and image generation so they aren't needed locally.

Assuming you haven't modified any packages (its fine if you did, just include them as well along with sources), you should have:
- `./SPECS/libdrm/libdrm.spec`,
- `./SPECS/libdrm/SOURCES/<source files & patches>` (Can also be in the `./SPECS/libdrm/` folder, but the SOURCES is recommended)
- `./toolkit`
- LICENSE etc...

Validate it worked with `sudo make input-srpms  REBUILD_TOOLS=y SRPM_FILE_SIGNATURE_HANDLING=update` (`DOWNLOAD_SRPMS=n` is implied, `SRPM_FILE_SIGNATURE_HANDLING=update` will generate the source file hashes for you automatically). This will scan the `./SPECS` folder for any packages and convert them into SRPMS.

**NOTE:** You didn't mention if you added libdrm to the image config. By default the system will include all packages in `toolkit/imageconfigs/packagelists/core-packages-image.json`, as referenced by the default image config `toolkit/imageconfigs/core-efi.json`. Make sure its added to this list so the build system knows it needs to be built.

Assuming that worked, `sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n` should now also work.

The build system will figure out the packages needed to build libdrm and download them, build libdrm, then figure out what packages are still missing for the final ISO. It will then download those, and combine them together into the final ISO.

**NOTE:** You might need to explicitly set the BuildRequires for libdrm, dynamic dependencies are coming soon to 2.0 (#141, #163).

*ps*: If you want a portable copy of the toolkit you can run `sudo make package-toolkit REBUILD_TOOLS=y` and setup shop in your own repo. Just extract the toolchain archive into ./toolchain inside the new folder.

**Comment by rradjabi** [comment]
Hi @dmcilvaney , I stepped away from needing to extend Mariner for a few months, but now I'm back. I'm trying to use your steps to build in support for 'smartpqi'. Which branch/tag do you recommend I use? Working in 1.0-stable, I used your suggestions above, but hit an issue eventually. I thought this was related to dynamic dependencies as you mentioned in your "NOTE".

> 
> `user@user-ProLiant-ML30-Gen10:~/Xilinx-Builds/CBL-Mariner/toolkit$ sudo make input-srpms REBUILD_TOOLS=y SRPM_FILE_SIGNATURE_HANDLING=update -j$(nproc)
> [sudo] password for user: 
> Makefile:13: CONFIG_FILE is empty, defaulting to toolkit's core-efi.json unless CONFIG_FILE="" was set explicitly.
> GODEBUG=x509ignoreCN=0 /home/user/Xilinx-Builds/CBL-Mariner/toolkit/out/tools/srpmpacker \
> 	--dir=/home/user/Xilinx-Builds/CBL-Mariner/toolkit/../SPECS \
> 	--output-dir=/home/user/Xilinx-Builds/CBL-Mariner/toolkit/../build/INTERMEDIATE_SRPMS \
> 	--source-url= \
> 	--dist-tag=.cm1 \
> 	--ca-cert= \
> 	--tls-cert= \
> 	--tls-key= \
> 	--build-dir=/home/user/Xilinx-Builds/CBL-Mariner/toolkit/../build/SRPM_packaging \
> 	--signature-handling=update
> WARN[0000] Will update signature files as needed        
> INFO[0000] Finding all SPEC files                       
> INFO[0000] Calculating SPECs to repack                  
> INFO[0000] Packing 1/1 SPECs                            
> PANI[0000] Unable to hydrate file: kmod-smartpqi-1.1.2-120.rhel7u4.x86_64.tar.bz2 
> panic: (*logrus.Entry) 0xc00021c230
> 
> goroutine 30 [running]:
> github.com/sirupsen/logrus.Entry.log(0xc00011e5b0, 0xc0002063f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> 	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x345
> github.com/sirupsen/logrus.(*Entry).Log(0xc00021c1c0, 0x0, 0xc000127868, 0x1, 0x1)
> 	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xf0
> github.com/sirupsen/logrus.(*Entry).Logf(0xc00021c1c0, 0xc000000000, 0x81cee2, 0x1a, 0xc0001279c0, 0x1, 0x1)
> 	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:333 +0xe5
> github.com/sirupsen/logrus.(*Logger).Logf(0xc00011e5b0, 0x0, 0x81cee2, 0x1a, 0xc0001279c0, 0x1, 0x1)
> 	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:146 +0x95
> github.com/sirupsen/logrus.(*Logger).Panicf(...)
> 	/home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:187
> main.hydrateFiles(0x1, 0xc00001c1e0, 0x4b, 0xc000058310, 0x61, 0xc00001a180, 0x38, 0x7fff8c43159e, 0x0, 0xc000071530, ...)
> 	/home/user/Xilinx-Builds/CBL-Mariner/toolkit/tools/srpmpacker/srpmpacker.go:605 +0x3ae
> main.packSingleSPEC(0xc00001c1e0, 0x4b, 0xc000058150, 0x65, 0xc00001a180, 0x56, 0x7fff8c4315e8, 0x44, 0xc000058150, 0x3d, ...)
> 	/home/user/Xilinx-Builds/CBL-Mariner/toolkit/tools/srpmpacker/srpmpacker.go:484 +0x57c
> main.packSRPMWorker(0xc00005cba0, 0xc00005cc00, 0x7fff8c4315b5, 0x4, 0x7fff8c4315e8, 0x44, 0x0, 0x0, 0x7fff8c43159e, 0x0, ...)
> 	/home/user/Xilinx-Builds/CBL-Mariner/toolkit/tools/srpmpacker/srpmpacker.go:390 +0x2bf
> created by main.packSRPMs
> 	/home/user/Xilinx-Builds/CBL-Mariner/toolkit/tools/srpmpacker/srpmpacker.go:344 +0x118
> /home/user/Xilinx-Builds/CBL-Mariner/toolkit/scripts/srpm_pack.mk:61: recipe for target '/home/user/Xilinx-Builds/CBL-Mariner/toolkit/../build/make_status/build_srpms.flag' failed
> make: *** [/home/user/Xilinx-Builds/CBL-Mariner/toolkit/../build/make_status/build_srpms.flag] Error 2
> `

**How do you suggest I add this package?**

**Comment by jslobodzian** [comment]
Where practical please clone the CBL-MarinerDemo repository (https://github.com/microsoft/CBL-MarinerDemo) and follow the associated tutorial.  This is an easier environment to experiment with building new packages.  Once the package builds, and if necessary, you can copy the SPEC file to a clone of CBL-Mariner and follow the standard build instructions for CBL-Mariner.
