### ISSUE TITLE
CBL-Mariner ISO not available

### ISSUE THREAD

**Issue by MarcoEnxuto** [microsoft/CBL-Mariner#1938]
Hi, the link provided on the Readme page returns request blocked.
https://aka.ms/mariner-1.0-x86_64-iso

**Comment by thcrain-msft** [comment]
Hopefully this is a transient error- I cannot reproduce this on my end, with or without our corporate VPN.

**Comment by MarcoEnxuto** [comment]
Hi @thcrain-msft, today is returning http 503. But on friday i could download it.

**Comment by mfrw** [comment]
@MarcoEnxuto I can confirm its a transient error as already mentioned by @thcrain-msft.
Can you please try again. It should work :)

**Comment by Banchio** [comment]
I tried for several days but unable to download, the aka.ms link redirects me to https://osrelease.download.prss.microsoft.com/pr/download/Mariner-1.0-x86_64.iso where I get a 403 Forbidden

**Comment by MarcoEnxuto** [comment]
It's now @mfrw . 
Better show with the screenshot. 
<img width="597" alt="image" src="https://user-images.githubusercontent.com/66541072/151659407-c1fef93d-0853-45ed-b73c-7eedfedbc8ce.png">

You might be blocking traffic outside the US, aren't you?

**Comment by Banchio** [comment]
I was able to download the ISO. I was not the issue opener but IMHO it can be closed.

**Comment by MarcoEnxuto** [comment]
> I was able to download the ISO. I was not the issue opener but IMHO it can be closed.

Confirmed. The link is now live. Thank you all.
