### ISSUE TITLE
ID_LIKE should reference RHEL

### ISSUE THREAD

**Issue by slaymaker1907** [microsoft/CBL-Mariner#2296]
Since Mariner seems to be intended as a mostly drop-in replacement for RHEL/CentOS/Fedora, the ID_LIKE variable should be set appropriately to reference this. This is used in a variety of dev tools by the SQL Server on Linux team in order to maintain maximum compatibility with various distros.

For reference, Amazon Linux does include this information in their /etc/os-release file.

```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

This is what Mariner seems to currently be using for /etc/os-release (docker run -it cblmariner.azurecr.io/base/core:1.0 /bin/bash):

```
NAME="Common Base Linux Mariner"
VERSION="1.0.20220127"
ID=mariner
VERSION_ID=1.0
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"
```

**Comment by eric-desrochers** [comment]
Mariner will be rebranded to Azure Linux. 

Since we are not a direct fork of RHEL, Centos,.. (despite the fact that we indeed are an RPM-based distribution) and are a distinct Linux distribution rich in Linux ancestors, we have no plan to implement a `ID_LIKE`  field for now.
