### ISSUE TITLE
Mariner /etc/os-release file is invalid

### ISSUE THREAD

**Issue by slaymaker1907** [microsoft/CBL-Mariner#2297]
/etc/os-release files are an extremely limited subset of shell syntax. They do not allow for unquoted strings unless it the strings are entirely in the range a-z, A-Z, or 0-9.

Therefore, `VERSION_ID=1.0` is not valid according to this syntax since the period character means that the entire value must be encased in quotes like `VERSION_ID="1.0"`.

The limited syntax of these files is extremely important since programs may wish to parse this file which do not include a shell interpreter.

```
user@computer:~$ docker run -it cblmariner.azurecr.io/base/core:1.0 /bin/bash
root [ / ]# cat /etc/os-release 
NAME="Common Base Linux Mariner"
VERSION="1.0.20220127"
ID=mariner
VERSION_ID=1.0
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"
root [ / ]# exit
exit
```

**Comment by PawelWMS** [comment]
That's a good catch, @slaymaker1907, thank you! I've started a PR to address this issue.
