### ISSUE TITLE
How to set static ip address?

### ISSUE THREAD

**Issue by kasini3000** [microsoft/CBL-Mariner#2479]
How to set static ip address?
Where is config file ?
What is the syntax for setting?
best to give an example

**Comment by terefang** [comment]
there is a config file under /etc/systemd/network/ but changing that according to systemd-networkd docuemtation does not work

**Comment by terefang** [comment]
research gives a PEBKAC.

create `/etc/systemd/network/20-eth0.network` file with the following contents
```
[Match]
Name=<interface>
[Network]
Address=<ip-Address>/<Mask>
Gateway=<gw-address>
DNS=<dns-address>
```

file must be readable by systemd user/group !

see `systemd-networkd` for details

**Comment by kasini3000** [comment]
Perfect! it work!  thanks, 
file /etc/systemd/network/20-eth0.network root 644
