### ISSUE TITLE
GitHub self-hosted-runners on Mariner

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/CBL-Mariner#2484]
When a customer using a Private-Endpoint in AKS or Azure Spring Cloud for instance, then a self-hosted-runner must be deployed in the same VNet.
Mariner is supported in [Azure DevOps self-hosted-runners,](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#check-prerequisites) but not in [GitHub Action self-hosted-runners.](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#linux)

RFE: Mariner to be supported in GitHub self-hosted-runners

**Comment by oliviacrain** [comment]
Looking at the comments in the [GitHub runners issue](https://github.com/actions/runner/issues/1750) and the [.NET Core issue](https://github.com/dotnet/core/issues/6379), it seems that this is not actionable on our part. This issue requires action by the .NET Core team first, then by the GitHub runner team. I'm going to close this for now- feel free to re-open this issue/open a new issue if there's some action we can take here.
