### ISSUE TITLE
adding support for nss-pam-ldapd/pam-tacacs/pam-radius

### ISSUE THREAD

**Issue by terefang** [microsoft/CBL-Mariner#2514]
is it possible to add support for nss-pam-ldapd and pam-tacacs and pam-radius

the use case would be for a environment that already contains these aaa services

References:
```
https://vault.centos.org/8.5.2111/AppStream/Source/SPackages/nss-pam-ldapd-0.9.9-3.el8.src.rpm
https://download-ib01.fedoraproject.org/pub/epel/8/Everything/SRPMS/Packages/p/pam_radius-1.4.0-15.el8.src.rpm
https://github.com/kravietz/pam_tacplus
```

**Comment by terefang** [comment]
hello

since CBL relies in part on photon-os for rpm-spec, i found
```
https://packages.vmware.com/photon/4.0/photon_srpms_4.0_x86_64/pam_tacplus-1.6.1-2.ph4.src.rpm
https://packages.vmware.com/photon/4.0/photon_srpms_4.0_x86_64/nss-pam-ldapd-0.9.11-1.ph4.src.rpm
```

**Comment by christopherco** [comment]
No plans to supply this today. We'll continue to re-evaluate this in the future. I invite you to fill out a feature request issue for this support to help us understand the proposed use-cases.
