### ISSUE TITLE
OOM fails on CBL-Mariner 2.0-stable

### ISSUE THREAD

**Issue by elsaco** [microsoft/CBL-Mariner#2656]
- git checkout 2.0-stable
- build ISO
- check `systemd --failed` output

Expected:
- `oomctl dump` to work

Actual results:
- `systemd-oomd.service` fails with `ConditionControlGroupController=v2 was not met`

Commit 404ea07 introduced `systemd.unified_cgroup_hierarchy=0` boot argument and forced `cgroups = V1`. This prevents `systemd-oomd.service` and `systemd-oomd.socket` to start, and breaks `oomctl dump` command. Removing this settings from `/boot/systemd.cfg` fixes the issue.

OS info:
```
NAME="Common Base Linux Mariner"
VERSION="2.0.20220325"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"
```

**Comment by cjp256** [comment]
Any reason this was closed? It seems to continue to affect latest Mariner image.
