### ISSUE TITLE
Proxy Variables not set in clone environment (chroot)

### ISSUE THREAD

**Issue by aditya-gulavani** [microsoft/CBL-Mariner#2672]
### Issue:
Unable to build basic ISO images behind proxy.

### Temporary Fix:
Manually add: `currentEnv = append(currentEnv, "HTTPS_PROXY=<PROXY-URL>")` to trackAndStartProcess routine in shell.go 

### Details:
I'm testing out the build instructions from [CBL-MarinerDemo](https://github.com/microsoft/CBL-MarinerDemo) and I got the following errors when running `make iso...`:

```
ERRO[0525] Failed to clone gcc(,):<ID:4 Type:Remote State:Unresolved> from '<NO_SRPM_PATH>' in '<NO_REPO>' from RPM repo. 
Error: No package gcc available
```

Make debug info points to:
```
DEBU[0526] stderr: curl#28: Timeout was reached
Error: TDNFGetRepoMD 1229
Error: Failed to synchronize cache for repo 'CBL-Mariner Official Base 1.0 x86_64' from 'https://packages.microsoft.com/cbl-mariner/1.0/prod/base/x86_64/rpms'
```

When I chroot manually to the build directory, I am able to get all the environment variables correctly. But it looks like the rpmrepocloner's shell environment does not get all the variables (dump only showed USER, SHELL, HOME, PATH variables).

The temporary fix above resolves the cloning issue and completes the ISO image build. Altough I think this might break something else.

What should be the right way to fix this?

**Comment by christopherco** [comment]
Mariner 1.0 is EOL. Closing this issue out as part of resolving out stale issues. Please open a new issue against 2.0 if this still a problem.
