### ISSUE TITLE
systemd-bootstrap-239-40.cm1.aarch64.rpm is required by toolkit 20220331-1.0 (tagged as release version) but package is not found on package server

### ISSUE THREAD

**Issue by yphuangms** [microsoft/CBL-Mariner#2703]
When using latest tagged release version 20220331-1.0 to build packages, following error happened:

        ERROR: Failed to download toolchain package: systemd-bootstrap-239-40.cm1.aarch64.rpm.

	Downloading toolchain RPM: systemd-bootstrap-239-40.cm1.aarch64.rpm
	--2022-04-12 10:22:26--  https://packages.microsoft.com/cbl-mariner/1.0/prod/base/aarch64/rpms/systemd-bootstrap-239-40.cm1.aarch64.rpm
	Resolving packages.microsoft.com (packages.microsoft.com)... 52.163.211.218
	Connecting to packages.microsoft.com (packages.microsoft.com)|52.163.211.218|:443... connected.
	HTTP request sent, awaiting response... 404 Not Found
	2022-04-12 10:22:27 ERROR 404: Not Found.
	
And double check on packages.microsoft.com server, there's no systemd-bootstrap-239-40.cm1.aarch64.rpm published under "https://packages.microsoft.com/cbl-mariner/1.0/prod/update/aarch64/rpms/".

This issue breaks package build and image build.

**Comment by yphuangms** [comment]
There have been times that the timing packages not being publish to server in time when using 1.0-stable, so we changed to use the latest version marked as release to ensure the condition of packages on server will go with toolkit.
Based on your suggestion to use 1.0-stable, does it ensure the packages required by 1.0-stable will always be published in time?

**Comment by elsaco** [comment]
@yphuangms add `USE_PREVIEW_REPO=y` to your build command.

**Comment by oliviacrain** [comment]
Following up and closing this issue- This package is now published for aarch64 and x86_64. This was an intermittent issue with our publishing process that was solved a couple of months back. In general, the `1.0-stable` tag should ensure that all relevant packages from that commit are uploaded to our RPM repos on packages.microsoft.com. If that is ever not the case, please feel free to open up another issue!
