### ISSUE TITLE
Mariner's docker image has no default shell

### ISSUE THREAD

**Issue by jiasli** [microsoft/CBL-Mariner#2751]
A common convention of Linux docker images is to have a default shell - `bash`:

```
> docker run -it --rm ubuntu:jammy

# ps -p $$
  PID TTY          TIME CMD
    1 pts/0    00:00:00 bash
```

However, Mariner's image doesn't have a default shell:

```
> docker run -it --rm cblmariner2preview.azurecr.io/base/core:2.0
docker: Error response from daemon: No command specified.
See 'docker run --help'.

> docker run -it --rm cblmariner2preview.azurecr.io/base/core:2.0 bash
root [ / ]#
```

This may not be very user-friendly.

See 

- https://www.cyberciti.biz/tips/how-do-i-find-out-what-shell-im-using.html
- https://docs.docker.com/engine/reference/builder/#cmd

**Comment by elsaco** [comment]
`CMD` is not mandatory. Having the user specify an `ENTRYPOINT` is okay.

**Comment by oliviacrain** [comment]
Thanks for the suggestion! This fix has been implemented for our 2.0 images going forward.

**Comment by jacqueskang** [comment]
Hi @elsaco,

We are facing an issue when building a custom image based on Mariner distroless image: We simply need to execute a bash script as entrypoint.

Would you please kindly provide instructions to install shell? I searched for hours without a clue.

Thanks

**Comment by TheOnlyWei** [comment]
@oliviacrain @elsaco I am still seeing this issue in 2.0, should this have been fixed? If I try to run the container, I just get this error:
```
PS C:\Users\weshi1> docker run -it --network host mcr.microsoft.com/cbl-mariner/distroless/base:2.0.20240609
docker: Error response from daemon: no command specified.
See 'docker run --help'.
```
I expected same behavior as a Linux distro like Ubuntu where it enters into the container in the bash shell.
