### ISSUE TITLE
Location of security advisories

### ISSUE THREAD

**Issue by gclair** [microsoft/CBL-Mariner#2847]
Apologies as this is less about a particular issue and more of a question, but when there are security updates?
Do you publish anywhere in the release/updates that CVE-xxx for package ABCD is fixed by going to version x.xx-y ?
Do you have plans to?

**Comment by oliviacrain** [comment]
Depending on the level of completeness you want, there's a couple of options for you. We publish a list of fixed CVEs in the [notes of each release](https://github.com/microsoft/CBL-Mariner/releases). We also provide up-to-date vulnerability data in the OVAL format over in [a different repository](https://github.com/microsoft/CBL-MarinerVulnerabilityData).

**Comment by oliviacrain** [comment]
Going to go ahead and close this issue, as the question has been answered. Feel free to re-open if you need any further details!
