### ISSUE TITLE
Use Python 3.10

### ISSUE THREAD

**Issue by jiasli** [microsoft/CBL-Mariner#2860]
The Mariner image currently contains Python 3.9:

```
> docker run -it --rm cblmariner2preview.azurecr.io/base/core:2.0 python3 -V
Python 3.9.10
```

According to https://www.python.org/downloads/release/python-3912/, Python 3.9 is already considered legacy:

> The release you're looking at is Python 3.9.12, a bugfix release for the **legacy** 3.9 series.

Also see https://peps.python.org/pep-0596/

Ubuntu 22.04 Jammy's Python is now Python 3.10:

```
> docker run -it --rm ubuntu:jammy

# apt update
# apt install python3
# python3 -V
Python 3.10.4
```

**Comment by oliviacrain** [comment]
Thanks for the feedback! We definitely appreciate that it is both a maintenance burden and a computational resource issue to support a larger testing matrix of Python versions. However, 3.9 is the version we settled on for our 2.0 releases after consultation with our internal customers regarding their overall needs. At this time, it is too late in our decision-making process to consider a newer version.

Even though 3.9 is considered "legacy", it is still in the bugfix support phase for another patch release and is supported with security updates until October 2025. The "legacy" label seems to be used for any release that is not part of the latest feature release series. Given that definition and the security support timeline, we don't consider 3.9 to be too out of date for Mariner's needs.

I'm going to go ahead and close this bug, as this is non-actionable for us. If you would like, I can put you in contact with our PM team so your feedback can be taken into account for future release cycles.

**Comment by KMoraz** [comment]
@oliviacrain any plans for 3.10 support?
