### ISSUE TITLE
Lynx & libguestfs

### ISSUE THREAD

**Issue by tr1al3x** [microsoft/CBL-Mariner#3019]
Hello Mariner,
I am trying to install lynx and libguestfs(for mounting/unmounting vhdx disks)
On both occasions I get "no packages" errors.

yum install lynx
Loaded plugin: tdnfrepogpgcheck
No package lynx available
Error(1011) : No matching packages 
----
yum install libguestfs
Loaded plugin: tdnfrepogpgcheck
No package libguestfs available
----

Is there a solution installing lynx/libguestfs?

Thank you.
AlexT

**Comment by PawelWMS** [comment]
Hi Alex,

These packages are only available in the [2.0 version of Mariner](https://github.com/microsoft/CBL-Mariner/tree/2.0-stable), so you'd need to try running your scenarios there.

**Comment by jslobodzian** [comment]
Closing issue as resolved.
