### ISSUE TITLE
[Feature Request] Mariner's tdnf repo should have specific versions of Python - `python39`

### ISSUE THREAD

**Issue by jiasli** [microsoft/CBL-Mariner#3058]
Red Hat Enterprise Linux has Python 3.6, 3.8, and 3.9 available in their yum repo: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_installing-and-using-python_configuring-basic-system-settings

The user can choose which version of Python to install using `python3`, `python38` and `python39`. 

Mariner, however, only has one `python3` which is 3.7 on Mariner 1.0 and 3.9 on Mariner 2.0.

```
# tdnf install python39
Loaded plugin: tdnfrepogpgcheck
python39 package not found or not installed
Error(1011) : No matching packages
```

It would be great if Mariner can also release `python39` package. This can make our build process easier (https://github.com/Azure/azure-cli/pull/22606). 

> Explicit is better than implicit.
> -- _[PEP 20 – The Zen of Python](https://peps.python.org/pep-0020/)_

Also see:

- https://github.com/microsoft/CBL-Mariner/issues/2860

**Comment by oliviacrain** [comment]
Thanks for the suggestion. I'll add the proper `Provides` statement in the spec file during the next update to the `python` package.

**Comment by oliviacrain** [comment]
Feature implemented, thanks for the feedback!
