### ISSUE TITLE
Deploy authenticated time sync via NTS in chrony

### ISSUE THREAD

**Issue by flawedworld** [microsoft/CBL-Mariner#3074]
Note that time.windows.com does not offer NTS currently. Can test with time.cloudflare.com though.

**Comment by christopherco** [comment]
Since our distribution is targeted towards Azure services, we follow the guidance here - https://learn.microsoft.com/en-us/azure/virtual-machines/linux/time-sync

Users are free to reconfigure, but the above is our default setting
