### ISSUE TITLE
Offer prebuilt-ca-certificates-microsoft package

### ISSUE THREAD

**Issue by ItalyPaleAle** [microsoft/CBL-Mariner#3094]
Just like there are prebuilt-ca-certificates (for ca-certificates) and prebuilt-ca-certificates-base (for ca-certificates-base), would it be possible to have prebuilt-ca-certificates-microsoft based on the ca-certificates-microsoft package?

We are using distroless images and we need to rely on prebuilt CA certificate bundles.

**Comment by PawelWMS** [comment]
The `prebuilt-ca-certificates` package provides the Microsoft bundle. Or, to be more precise, it provides the same set of packages as `ca-certificates` and that package contains the Microsoft bundle. Currently `ca-certificates-microsoft` should treated like an alias for `ca-certificates`.

Having said all that, it's a good idea to make `prebuilt-ca-certificates-microsoft` an alias for `prebuilt-ca-certificates`, so we're consistent. Thanks!

**Comment by ItalyPaleAle** [comment]
Hi @PawelWMS thanks for responding. Can you please clarify this:

>  Currently ca-certificates-microsoft should treated like an alias for ca-certificates.

According to the docs ([internal link](https://eng.ms/docs/products/mariner-linux/gettingstarted/containers/distroless)):

> Install ca-certificates-microsoft for the official Microsoft [curated set of trusted root certificates](https://ccadb-public.secure.force.com/microsoft/IncludedCACertificateReportForMSFT) (recommended) or ca-certificates for the set of Mozilla Trusted Root Certificates.

Are you saying that the docs are incorrect and both ca-certificates and ca-certificates-microsoft use the Microsoft-curated CA certs?

**Comment by PawelWMS** [comment]
Updated documentation and our packages. Closing the issue.
