### ISSUE TITLE
Tool to update packages

### ISSUE THREAD

**Issue by lpereira** [microsoft/CBL-Mariner#31]
Updating packages in Mariner takes a lot of manual steps, and this isn't really good for the velocity we need to address security vulnerabilities in the tight SLAs we're working with.  I'd like a tool that would automate a lot of these things:

- Bump the package release automatically.
- Create a new changelog entry (using my name/email from the Git configuration), possibly opening in `$EDITOR`.
- Update the manifests for all the subpackages in the spec file.
- If you're updating a package to the new version, try to guess the URL automatically by changing the old version in the URL to the new version; if it doesn't work, it can ask the actual URL for the new version. Regardless, it should update the `*.signatures.json` files.
- If it's a package that's flagged to be part of the toolchain, some additional steps might be involved.
- It can optionally build the package to see if it works, determining the build-dep packages from the specfile and building them too.
- Once everything is said and done, it'll create a new Git commit with the changes; the message can include the specfile changelog entry.

I was thinking about this for the CLI interface; for instance, to update a package to a new upstream version:

```
$ mariner-up bash --new-upstream
Currently packaged version is 4.9.
Source currently lives in https://some/gnu/mirror/bash-4.9.tar.gz

*** New version? 5.0

Trying to fetch version 5.0 from https://some/gnu/mirror/bash-5.0.tar.gz
Fetch successful, using this URL for the new source tarball.

Bumping package release from 29 to 30.
Creating ChangeLog entry:
    Mon Aug 17 2020 Leandro Pereira <leperei@microsoft.com> 5.0-30
    - Update to upstream version 5.0.

*** Edit with /usr/bin/joe (y/N)? n

Git commit created.

*** Package has not been built; verify it builds and update manifests (Y/n)? Y

Building package. Follow progress in /tmp/asdfasdasdf-bash.log
Package built successfully in 00:03:37.
Updating manifests and amending Git commit.
```

Some of the questions that are asked could be passed as command-line arguments (e.g. `--build-package` to avoid asking if you want to build the package).

@microsoft/cbl-mariner-devs: Questions? Comments? Suggestions?

**Comment by jslobodzian** [comment]
Thank you for your suggestion.  At this time your suggestion is being tracked internally for future consideration.
