### ISSUE TITLE
add mstflint to Mariner OS

### ISSUE THREAD

**Issue by moshe010** [microsoft/CBL-Mariner#3137]
mstflint Package - Firmware Burning and Diagnostics Tools for Nvidia NICs. [1] 
Can you please add mstflint Package to Mariner OS? This will allow trouble-shooting and diagnostics Nvidia Firmware  

[1] - https://github.com/Mellanox/mstflint

**Comment by mfrw** [comment]
Closing issue as feature merged via PR: #3641.
