### ISSUE TITLE
Add option to compile packages with -fno-omit-frame-pointer

### ISSUE THREAD

**Issue by mjsabby** [microsoft/CBL-Mariner#321]
Frame pointers are critical for production profiling, which is crucial for running production services.

I propose we have an option in Mariner that supports compiling all packages with this option and providing a flavor of this build to customers.

It would be great if Mariner became the first Linux distribution that had a flavor for frame pointers disabled.

**Comment by jslobodzian** [comment]
We have discussed the option of enabling frame pointers, however this comes with a performance penalty, and is understood to be an all-or-nothing situation.  For now frame pointers will not be supported.
