### ISSUE TITLE
mariner amd dist latest + node.js 18 support

### ISSUE THREAD

**Issue by ranshamay** [microsoft/CBL-Mariner#3231]
hi,
i would like to ask couple of questions

1. is there a way to get the latest tag of amd64 distribution of the image? following the docs, i must specify full image version to pin the amd64 architecture  - for instance - 16.14.2-2-cm2.0.20220527-amd64
2. is there a way to get node18 installed on the image/ is there any node 18 image i can use?

thanks!

**Comment by mandeepsplaha** [comment]
Hi @ranshamay.
1. You can query this url: `https://mcr.microsoft.com/v2/cbl-mariner/base/nodejs/tags/list` to get the available tags for nodejs container image. You don't necessarily have to pin to a specific image version. It depends on whether you would like to stay on the latest major `nodejs` version, in which case, you could just choose the `16` tag. If you want to stay on a specific major.minor version then you could pin to `16.14`. The tags also offer a way to stay on the nodejs version with a specific `mariner` version i.e., `16-cm2.0`, `16.14-cm2.0`.
2. Mariner only offers nodejs version `16` at the moment so unfortunately you wouldn't be able to upgrade to `18` until Mariner starts to offer it.

I hope that helps.

**Comment by scovetta** [comment]
Is there an update on Node.js 18? Node 16 enters maintenance in October 2022.

**Comment by Ohad-Fein** [comment]
Any updates?
Maybe from @mandeepsplaha side?

**Comment by cliffordfajardo** [comment]
Hey fellow Microsofters 👋 ,
Visited the link that @mandeepsplaha referenced here
https://mcr.microsoft.com/v2/cbl-mariner/base/nodejs/tags/list and it looks like it only goes up to node `16.8` at the time of this comment

![CleanShot 2022-12-22 at 09 41 16@2x](https://user-images.githubusercontent.com/6743796/209194370-60415faf-1c97-414c-b3e1-1323bb429911.png)


@mandeepsplaha - which upstream team (or person) can we talk to discuss node 18 support? 
Do you know if there is a timeline for the nodejs updates?

**Comment by jeffwilcox** [comment]
+1, watching. We moved a bunch of images from Ubuntu to Mariner expecting to have access to LTS Node builds.

**Comment by mandeepsplaha** [comment]
I sincerely apologize that I haven't replied to the above requests sooner.

We have an update on nodejs 18 container image. We have just released the nodejs 18 container image through MCR. This [link](https://mcr.microsoft.com/v2/cbl-mariner/base/nodejs/tags/list) is still valid to query the available tags for this image. Additionally, you can also use the MAR (Microsoft Artifact Registry) portal for more information on [CBL-Mariner NodeJS](https://mcr.microsoft.com/en-us/product/cbl-mariner/base/nodejs/about) container image.

**Comment by jeffwilcox** [comment]
Thank you so much!
