### ISSUE TITLE
`useradd` command not found in CBL Mariner 2.0 despite existing in 1.0

### ISSUE THREAD

**Issue by mpwillia** [microsoft/CBL-Mariner#3239]
While migrating to mariner images I found that the `useradd` command is not available in the base CBL Mariner 2.0 image despite being available in the 1.0 image.

In 1.0 I observe the following.
```
> docker run -it --entrypoint /bin/bash mcr.microsoft.com/cbl-mariner/base/core:1.0
root [ / ]# useradd
Usage: useradd [options] LOGIN
       useradd -D
       useradd -D [options]

... truncated useradd help page ...
```

While in 2.0 I observe the following.
```
> docker run -it --entrypoint /bin/bash mcr.microsoft.com/cbl-mariner/base/core:2.0
root [ / ]# useradd
bash: useradd: command not found
```

I expected the `useradd` command to exist regardless of which version I used.

**Comment by PawelWMS** [comment]
There is no backward compatibility between 2.0 and 1.0, so it is possible that the `shadow-utils` package in not part of the base image anymore. You can still install it, if needed.

**Comment by mpwillia** [comment]
> it is possible that the shadow-utils package in not part of the base image anymore. You can still install it, if needed.

Ah perfect, it wasn't clear to me that `adduser` was coming from `shadow-utils` being preinstalled in 1.0.
Installing the package will work perfectly fine for my use case. Thank you!
