### ISSUE TITLE
suspicious: `if` with identical branches at `toolkit/tools/internal/safechroot/safechroot_test.go`

### ISSUE THREAD

**Issue by chavacava** [microsoft/CBL-Mariner#3244]
Both `then` and `else` blocks are identical in the code below

https://github.com/microsoft/CBL-Mariner/blob/1efa284885f39a4257fe982fe047e3269268d2f3/toolkit/tools/internal/safechroot/safechroot_test.go#L71-L75

Spotted by [`revive`](https://github.com/mgechev/revive) rule `identical-branches`

**Comment by mfrw** [comment]
Ahh! thank you @chavacava. Will do some digging on the ` TestInitializeShouldCreateRoot` :)

**Comment by mfrw** [comment]
Fixed with PR:
- #3498
