### ISSUE TITLE
When GDB debug  exe with dump , it can't load symbols 

### ISSUE THREAD

**Issue by LiangJy123** [microsoft/CBL-Mariner#3296]
Hi ,
When I use GDB to debug my exe in Mariner, I meet a problem as the title suggests.
![image](https://user-images.githubusercontent.com/13048899/177142987-fd34ee99-ce6d-4ffa-81ca-420ba52acd61.png)
The core dump file is match the executable file.

The same  operation in Ubuntu2204 is normal.
![image](https://user-images.githubusercontent.com/13048899/177145883-ade6442b-43d9-4a6a-bbe5-1986f47a36e5.png)

Another strange thing is the dump name genarated in Mariner.

Core pattern is "/corefile/core-%e-%p-%t".
%e means executable file name without path.
But the dump name is "core-sudo-xxx-xxx" .
"sudo" is not my executable file name.
![image](https://user-images.githubusercontent.com/13048899/177144658-866ef1ea-1626-4166-acf0-0d97aab883ea.png)

So is the GDB not work normally in this situation  ? 

System info:
Linux cbl-mariner-HFPKyCC2mFvu 5.15.41.1-1.cm2 #1 SMP Sat May 28 19:48:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mfrw** [comment]
Hi @LiangJy123 can you try to give more details. Like e.g the output of `cat /etc/os-release` & also the version of `gcc & gdb`.
Did we add the `-g` option to `gcc` while compiling.
Also, the can we please try running without the `sudo` prefix.

For reference:

![image](https://user-images.githubusercontent.com/4929861/177325286-985fc39b-c401-4526-b08d-5acf589412fe.png)

**Comment by LiangJy123** [comment]
Hi  @mfrw , thank you for your reply.

I'm sure using gcc with  -g option when compiling.
It looks well on your screenshot.

But there is no dump created without  using **sudo** , Is there a  permission mistake with current user ?
![image](https://user-images.githubusercontent.com/13048899/177493981-d7f94563-84eb-4152-a722-70474836d28b.png)

os-release
```
NAME="Common Base Linux Mariner"
VERSION="2.0.20220625"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"
```
gcc
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/11.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ./configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-languages=c,c++,fortran --disable-multilib --disable-bootstrap --enable-linker-build-id --enable-plugin --enable-default-pie --with-system-zlib
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (GCC)
```

gdb
```
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by mfrw** [comment]
> But my result is not same as yours , there is no dump created without using sudo .

@LiangJy123 I think a few pointers that I suspect might be the cause of this:
- Is our `/corefile` dir writeable by the user that is running the program?
- Can we try the latest version of Mariner `VERSION="2.0.20220617"`


I tried to reproduce the issue using the latest release, but could not.

Reference: 
![image](https://user-images.githubusercontent.com/4929861/177509571-e0151d32-52e7-46ba-bb42-dbe18d97a52a.png)

Feel free to reachout offline if we still get the issue :)

**Comment by LiangJy123** [comment]
Thanks for your help  @mfrw .
It works for me when  changing "/corefile"  dir to be writeable.
Without using **sudo** , GDB works well.
![image](https://user-images.githubusercontent.com/13048899/177527298-4506af58-7f2b-4bf0-b6c2-944d05c10456.png)

It's a common issue  and forgive me for not being very familiar with Linux .

By the way , I am interesting  with Mariner and  is there any document about how to build a custom kernel module on Mariner ?

**Comment by mfrw** [comment]
There should not be any special steps involved in building a kernel module on `Mariner`.
The normal steps which we follow on any standard distro should be applicable here as well.
