### ISSUE TITLE
[2.0] `TestShouldPassCreatingNetworkFile_Network` fails on systems without `systemd-networkd`

### ISSUE THREAD

**Issue by onalante-msft** [microsoft/CBL-Mariner#3483]
Root cause: https://github.com/microsoft/CBL-Mariner/blob/d46675bc0fbc0e562386034e9e54e46568477d26/toolkit/tools/imagegen/configuration/networkconfig_test.go#L137

The test rightly complains about the directory `/etc/systemd/network` not existing on systems without `systemd-networkd`, breaking the `package-toolkit` target.

**Comment by onalante-msft** [comment]
Patch and workaround proposals can be found in #3486.

**Comment by PawelWMS** [comment]
@henryli001, could you take a look at this issue? It is causing issues with building our toolkit on some systems. I'm wondering, if we shouldn't be creating the missing directory in such cases, instead of assuming it should be present.

**Comment by henryli001** [comment]
Has opened a PR to resolve this issue: https://github.com/microsoft/CBL-Mariner/pull/3614

**Comment by onalante-msft** [comment]
Should the issue remain open until the PR changes are merged into 2.0, or would you prefer that I close it now?

**Comment by yophilav** [comment]
@henryli001 
Do you have an estimated date for the release contain this bugfix? 
The release [2.0.20220824-2.0](https://github.com/microsoft/CBL-Mariner/releases/tag/2.0.20220824-2.0) was out but this bug didn't make the cut.  Thanks!
