### ISSUE TITLE
Why is ca-certificates not installed in `core` Docker image?

### ISSUE THREAD

**Issue by dagood** [microsoft/CBL-Mariner#3563]
My team produces Go images, like these:
```
mcr.microsoft.com/oss/go/microsoft/golang:1.19.0-1-cbl-mariner2.0-amd64
mcr.microsoft.com/oss/go/microsoft/golang:1.19.0-1-bullseye-amd64
```

A team trying to use our images let us know that they weren't able to use the Go proxy properly on the CBL-Mariner images. They are based on the "core" images, `cblmariner.azurecr.io/base/core:2.0`. Simple repro:

```
$ docker run -it --rm mcr.microsoft.com/oss/go/microsoft/golang:1.19.0-1-cbl-mariner2.0-amd64 wget https://proxy.golang.org/k8s.io/client-go/@v/v0.24.1.zip
[...]
--2022-08-17 17:33:40--  https://proxy.golang.org/k8s.io/client-go/@v/v0.24.1.zip
Resolving proxy.golang.org... 142.250.69.209, 2607:f8b0:400a:805::2011
Connecting to proxy.golang.org|142.250.69.209|:443... connected.
ERROR: cannot verify proxy.golang.org's certificate, issued by 'CN=GTS CA 1C3,O=Google Trust Services LLC,C=US':
  Unable to locally verify the issuer's authority.
To connect to proxy.golang.org insecurely, use `--no-check-certificate'.
```

If I `tdnf install -y ca-certificates` before running the download, it works. The Debian bullseye image already has `ca-certificates` installed, so this step isn't necessary with that image.

In https://github.com/microsoft/CBL-Mariner/issues/2298, a comment says this is by design.

* What is the reason behind this choice?
* Is there a reason that we shouldn't include ca-certificates in our Go images in particular?

**Comment by dagood** [comment]
The core and distroless images do have some certs installed, but not quite `ca-certificates`:

https://github.com/microsoft/CBL-Mariner/blob/50e2132e5a911b049c1f3dd83786c8f3d2a58887/SPECS/distroless-packages/distroless-packages.spec#L16

https://github.com/microsoft/CBL-Mariner/blob/50e2132e5a911b049c1f3dd83786c8f3d2a58887/SPECS/core-packages/core-packages.spec#L56

**Comment by PawelWMS** [comment]
Hi, @dagood! The core images by design contain only `ca-certificates-base`, which is the minimal set to have the images operational (for instance install other packages). We do not include `ca-certificates` to limit the image size. It is completely fine, however, to install whatever additional packages your scenarios might require.

**Comment by dagood** [comment]
Ok, thanks. Since it's just for image size, definitely makes sense to include in our builder images to make them more usable.
