### ISSUE TITLE
Azure cloud shell is pointing to Old helm version. It should be updated to latest version 3.9.3.

### ISSUE THREAD

**Issue by KRISHNA-VKS** [microsoft/CBL-Mariner#3593]
execute the command in azure cloud shell
"rpm -qa"
It says "helm-**3.4.1**-5.cm2.x86_64".
This is very very old release of helm. 

We are already in helm **3.9.3** as per release https://github.com/helm/helm/releases/tag/v3.9.3

Due to this, **helm push** command is not available in cloud shell.

![image](https://user-images.githubusercontent.com/108654838/186080408-6585e776-7cb5-4cd9-8574-0e2a30c2d8c5.png)

The extensive details are mentioned here:-  https://github.com/Azure/CloudShell/issues/236

Expected result:-
![image](https://user-images.githubusercontent.com/108654838/186080631-ce9e3a7e-41ae-4814-9352-91641ee7964f.png)

**Comment by PawelWMS** [comment]
I see that @chalamalasetty has just updated `helm` in #3586. I'm guessing you synced with him offline but I'm mentioning it here just in case. The new version should be available at the latest with our next release in 2-3 weeks.

**Comment by mfrw** [comment]
Closing issue as per PR:
- #3586 

Please re-open if there are any further clarifications/questions :)
