### ISSUE TITLE
CNCF TAG-Runtime Discussion/Presentation?

### ISSUE THREAD

**Issue by raravena80** [microsoft/CBL-Mariner#3749]
Hello CBL-Mariner team,

I'm one of the co-chairs of the CNCF TAG-Runtime, I'm reaching out and I think it would be great for you to present/discuss the project at one of our meetings. A general overview of the project, community and maybe a demo would be great.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks

**Comment by jperrin** [comment]
I think this would be good. I'll see about adding it to the agenda.

**Comment by oliviacrain** [comment]
Looks like our folks were in attendance at the 3 Nov 2023 meeting- closing out this issue.
