### ISSUE TITLE
[feature request] install blobfuse2 on Mariner 2.0

### ISSUE THREAD

**Issue by andyzhangx** [microsoft/CBL-Mariner#3772]
https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview.3

and then install blobfuse2 in AKS AgentBaker: https://github.com/Azure/AgentBaker/blob/2baa4c915635a1c24cb70106b3e63654d8023da6/parts/linux/cloud-init/artifacts/mariner/cse_install_mariner.sh#L12

Motivation:
We want to test blobfuse2 in Mariner 2.0 in early stage on AKS, thanks.

**Comment by mfrw** [comment]
Closing - feature merged as per PR:
- https://github.com/microsoft/CBL-Mariner/pull/3890
