### ISSUE TITLE
URGENT: No Package manager installed with Mariner 2.0

### ISSUE THREAD

**Issue by adiiot-1316** [microsoft/CBL-Mariner#3878]
Hi , 

I am trying to install few packages , but unfortunately no package manager like Dnf , TDNF, apt , yum is installed. 
What could be the reason?
Is there a way to install the package manager manually using CURL etc? 

**Details of Mariner OS**

DISTRIB_ID="Mariner"
DISTRIB_RELEASE="2.0.20220824"
DISTRIB_CODENAME=Mariner
DISTRIB_DESCRIPTION="CBL-Mariner 2.0.20220824"
CBL-Mariner 2.0.20220824
NAME="Common Base Linux Mariner"
VERSION="2.0.20220824"
ID=mariner
VERSION_ID="2.0"

Please let me know if you need any additional details.

**Comment by mfrw** [comment]
This seems a little odd, can you please give more info on what are you using ?
Could you please give us some steps to repro this. What did you do, what was the expectation and what happened.
We do have `rpm/tdnf` installed in the image by default.

> Please let me know if you need any additional details.

What is the output of:
- `which tdnf`
- `which rpm`
- `which yum`

I unfortunately am unable to repro it, and it works as expected:

![image](https://user-images.githubusercontent.com/4929861/193379747-a7e67321-ccb7-495a-9abf-7b9f74f82c93.png)

The az-cli command to spawn this vm: 
```bash
az vm create --name test-vm --resource-group delete --location centralindia --image MicrosoftCBLMariner:cbl-mariner:cbl-mariner-2:latest --os-disk-size-gb 32 --admin-username mfrw
```

**Comment by adiiot-1316** [comment]
Thanks Wani for your prompt response, 

I tried the above commands and below are the responses. 

`iotedge-user@iotedge-vm [ ~ ]$ which tdnf
which: no tdnf in (/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin)
iotedge-user@iotedge-vm [ ~ ]$ which yum
which: no yum in (/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin)
iotedge-user@iotedge-vm [ ~ ]$ which rpm
which: no rpm in (/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin)`

**Comment by mfrw** [comment]
This is very strange :(

Please feel free to reach-out offline; we would want some post-mortem of this issue so that it does not happen again.

**Comment by adiiot-1316** [comment]
We have using Azure Edge IoT i.e. azure iot edge for linux on windows (eflow) in which CBL Mariner is pre-installed. But no package manager is installed in that CBL mariner .

**Comment by christopherco** [comment]
Hi @adiiot-1316 , this may actually be expected. EFLOW is a very purpose-built offering, whose composition may not include the package manager. Tagging @adithyaj and @josephknierman
