### ISSUE TITLE
CBL-Mariner 2.0 Marketplace image comes with a 1.5GB OS Disk

### ISSUE THREAD

**Issue by johanburati** [microsoft/CBL-Mariner#4040]
Just deployed a gen2 VM  using latest image *MicrosoftCBLMariner:cbl-mariner:cbl-mariner-2-gen2:2.20221010.01*
and it came up with a 1.5GB  OS disk, the root partition  is full and it breaks things:

```
$ cat /etc/mariner-release
CBL-Mariner 2.0.20221010
MARINER_BUILD_NUMBER=4511636

$ sudo dnf listrepo
error: sqlite failure: CREATE TABLE IF NOT EXISTS 'Packages' (hnum INTEGER PRIMARY KEY AUTOINCREMENT,blob BLOB NOT NULL): disk I/O error
error: cannot open Packages index using sqlite - No such file or directory (2)
error: cannot open Packages database in /var/lib/rpm
Error: Error: rpmdb open failed

$ echo foo > bar
-bash: echo: write error: No space left on device

$ df .
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/sda3         978972 962588         0 100% /

$ lsblk /dev/sda
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda      8:0    0  1.5G  0 disk
|-sda1   8:1    0    8M  0 part /boot/efi
|-sda2   8:2    0  500M  0 part /boot
`-sda3   8:3    0  990M  0 part /
```

**Comment by PawelWMS** [comment]
Hi, @johanburati! Thank you for letting us know.

Could you provide more details about how you set-up your VM, which VM size you've used, what was the OS disk type you've chosen and any additional configuration parameters? I've tried reproing the issue with the `Standard_D2s_V3` machine size and `Premium SSD` disk type but to no avail.

**Comment by johanburati** [comment]
> Could you provide more details about how you set-up your VM, which VM size you've used, what was the OS disk type you've chosen and any additional configuration parameters? I've tried reproing the issue with the `Standard_D2s_V3` machine size and `Premium SSD` disk type but to no avail.

I've created the vm using azure cli  such as ` az vm create -g mariner -n mariner --image MicrosoftCBLMariner:cbl-mariner:cbl-mariner-2-gen2:latest --size Standard_D2s_v3`  did not specify any OS disk attribute. I use the same command for other distro without issues.

```
offer:cbl-mariner
publisher:MicrosoftCBLMariner
sku:cbl-mariner-2-gen2
version:2.20221010.01
vmSize:Standard_D2s_v3

$ df -Ph /
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3       957M  941M     0 100% /

$ lsblk /dev/sda
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda      8:0    0  1.5G  0 disk
|-sda1   8:1    0    8M  0 part /boot/efi
|-sda2   8:2    0  500M  0 part /boot
`-sda3   8:3    0  990M  0 part /
```

**Comment by christopherco** [comment]
Mariner's Marketplace image supplies just the OS in a default offering (~1.5GB) while other distros in Azure tend to supply ~30GB by default. The OS disk size itself is a settable parameter via az cli `--os-disk-size-gb <size> ` or via ARM template which allows you to choose the OS disk size that suits your purposes.

**Comment by johanburati** [comment]
Yes, I could use the `--os-disk-size-gb` option, but wouldn't it better to resize the image size to 5GB so that it just works out of the box ?

**Comment by christopherco** [comment]
Will take in this feedback and see what we can do.

We don't necessarily want to increase the size of our default backing image, as this would unnecessarily increase backing resources used and time spent replicating / publishing. That being said, there are a couple other paths I'd like to explore to see if we can get the same desired end result.

In the meantime though, `--os-disk-size-gb` is the recommended option.

**Comment by christopherco** [comment]
FYI - We have updated the image sizes in our latest CBL-Mariner 2.0 Marketplace images to be 5GB. Thank you @aditjha-msft for making these changes!

@johanburati Please try them out and let us know any feedback

**Comment by christopherco** [comment]
Now that the Marketplace images disk sizes are increased, closing out issue.

Please feel free to reopen if there is anything on this topic that we can help address.
