### ISSUE TITLE
CBL-Mariner ARM based images

### ISSUE THREAD

**Issue by lukebakare** [microsoft/CBL-Mariner#4059]
Can you provide arm64/aarch64 based images for CBL-Mariner 2.0 in VHD/VHDX formats?

For reference the following image MicrosoftCBLMariner:cbl-mariner:cbl-mariner-2-arm64:latest is available on Azure.
There is also no arm64 ISO file in the README.md, only x64 is listed.

**Comment by lukebakare** [comment]
After reviewing the issues thread I have built the required image formats for arm64:

VHD
`sudo make image REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/marketplace-gen2-aarch64.json`

VHDX
`sudo make image REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/core-efi-aarch64.json`

ISO
`sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full-aarch64.json`

**Comment by paulzzy** [comment]
For others looking to build for aarch64, please note that cross-compiling is not supported (per https://github.com/microsoft/CBL-Mariner/issues/133#issuecomment-830758578). Must build CBL Mariner natively on an aarch64 host machine.
