### ISSUE TITLE
Use rootfs file-system other than EXT4?

### ISSUE THREAD

**Issue by i2** [microsoft/CBL-Mariner#4131]
Hi everyone,

Is it possible to have a rootfs whose file-system is other than EXT4 file-system? For instance, let's say BTRFS?

**Comment by PawelWMS** [comment]
Hi there!

I'm afraid BTRFS is not supported. Mariner is mostly focused around EXT (and FAT for `/boot/efi`).

You can play around with a few other formatting options in the [ISO installer](https://aka.ms/mariner-2.0-x86_64-iso) when you select manual formatting but they are closer to an experimental feature at the moment.

**Comment by i2** [comment]
Knowing close ties between CBL-Mariner and WSL2, can an experimental rootfs filesystem for WSL2 other than EXT4 be achieved? Thanks!

**Comment by i2** [comment]
Now that XFS as rootfs is possible, I think this question can be revisited. Thanks!

**Comment by eric-desrochers** [comment]
We do have EXT4 and XFS.

https://github.com/microsoft/CBL-Mariner/blob/2.0/toolkit/docs/formats/imageconfig.md

![image](https://github.com/microsoft/CBL-Mariner/assets/98553622/ff6631c6-4484-4051-baa6-a2b8acda50ca)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/CBL-Mariner/issues/4131#issuecomment-1845883616

#eric-desrochers, why *not* BTRFS, though? It's markedly superior.

**Comment by i2** [comment]
Thanks for the response @eric-desrochers Nonetheless, I'd appreciate if this issue could be left open! IMHO, in future this would be crucial for WSL2/CBL-Mariner.
