### ISSUE TITLE
SRPM Hydration Randomly Failing on make toolchain

### ISSUE THREAD

**Issue by sr229** [microsoft/CBL-Mariner#421]
We're making our own fork of CBL-Mariner but we keep encountering issues where some packages randomly fail hydration, the usual culprits were `GSL`, `Cython`, `ant-contrib`, `ant`, `acl` and ALSA packages. 

The hydration errors only happen when you're completely building from source.

**Comment by dmcilvaney** [comment]
Its likely there is a general failure across all packages, the `srpmpacker` tool runs 10 workers in parallel so its quite reasonable for it to report a set of failures then exit.

Could you post the errors with `LOG_LEVEL=trace`? (I don't expect much more detail from `srpmpacker` however)

**Comment by sr229** [comment]
there isn't much with `LOG_LEVEL=trace` since it yields the same error message.. 
```
PANI[0008] Unable to hydrate file: maven-ant-tasks-2.1.3.tar.gz 
PANI[0008] Unable to hydrate file: ansible-2.9.9.tar.gz 
panic: (*logrus.Entry) 0xc0002361c0

goroutine 2553 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0001265b0, 0xc000431230, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc000236150, 0x0, 0xc000093868, 0x1, 0x1)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xf0
github.com/sirupsen/logrus.(*Entry).Logf(0xc000236150, 0xc000000000, 0x81bd82, 0x1a, 0xc0000939c0, 0x1, 0x1)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:333 +0xe5
github.com/sirupsen/logrus.(*Logger).Logf(0xc0001265b0, 0x0, 0x81bd82, 0x1a, 0xc0000939c0, 0x1, 0x1)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:146 +0x95
github.com/sirupsen/logrus.(*Logger).Panicf(...)
        /root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:187
main.hydrateFiles(0x1, 0xc0001a2080, 0x33, 0xc0001500a0, 0x4e, 0xc0001800c0, 0x2a, 0x7ffdd508d4e6, 0x0, 0xc00007b470, ...)
        /home/chinodesuuu/Amelia-Mariner/toolkit/tools/srpmpacker/srpmpacker.go:605 +0x3ae
main.packSingleSPEC(0xc0001a2080, 0x33, 0xc00019c0c0, 0x52, 0xc0001800c0, 0x3e, 0x7ffdd508d530, 0x40, 0xc00019c0c0, 0x39, ...)
        /home/chinodesuuu/Amelia-Mariner/toolkit/tools/srpmpacker/srpmpacker.go:484 +0x57c
main.packSRPMWorker(0xc0004a4780, 0xc0004a47e0, 0x7ffdd508d4fd, 0x4, 0x7ffdd508d530, 0x40, 0x0, 0x0, 0x7ffdd508d4e6, 0x0, ...)
        /home/chinodesuuu/Amelia-Mariner/toolkit/tools/srpmpacker/srpmpacker.go:390 +0x2bf
created by main.packSRPMs
        /home/chinodesuuu/Amelia-Mariner/toolkit/tools/srpmpacker/srpmpacker.go:344 +0x118
make: *** [/home/chinodesuuu/Amelia-Mariner/toolkit/scripts/srpm_pack.mk:61: /home/chinodesuuu/Amelia-Mariner/toolkit/../build/make_status/build_srpms.flag] Error 2
```

**Comment by dmcilvaney** [comment]
If `SOURCE_URL` is set, I would expect something along the lines of `Failed to download (https://yoursources.com/a/source). Error: Some Error` towards the end of the log. (I've asked internally to see if we have some documentation about what is needed for your own source server, its not something I'm familiar with personally).

Assuming its not set, the missing sources would need to be available locally next to the *.spec files. You would need to place `ansible-2.9.9.tar.gz` at `CBL-Mariner/SPECS/ansible/SOURCES/ansible-2.9.9.tar.gz` (Note, the `SOURCE/` part is optional, it will also look in the ansible/ folder directly).

Each package also has a `package.signatures.json` file containing hashes of the expected source files. If you are swapping sources around you may need to update that (either manually, or you can build with `SRPM_FILE_SIGNATURE_HANDLING=update`.

**Comment by sr229** [comment]
Unfortunately, we didn't set a SOURCE_URL so I directly assume it's not going to matter that much since we thought it's pulling sources from the SPEC file URLs provided or from cgmanifest.

**Comment by jslobodzian** [comment]
CBL-Mariner continues to publish SRPMs, but starting from the March update, CBL-Mariner pulls source tar files from a public blobstore.  The source URL can be set as follows: SOURCE_URL=https://cblmarinerstorage.blob.core.windows.net/sources/core
