### ISSUE TITLE
Unable to start dockerd on Mariner VM

### ISSUE THREAD

**Issue by savaradh** [microsoft/CBL-Mariner#4357]
I am getting the following error when I try to start dockerd on the VM created using Mariner.

```
INFO[2022-12-02T23:37:25.631314721Z] Loading containers: start.
WARN[2022-12-02T23:37:25.632681458Z] Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module bridge not found in directory /lib/modules/5.15.77.1-1.cm2
modprobe: WARNING: Module br_netfilter not found in directory /lib/modules/5.15.77.1-1.cm2
, error: exit status 1
WARN[2022-12-02T23:37:25.673436458Z] Could not load necessary modules for IPSEC rules: protocol not supported
WARN[2022-12-02T23:37:25.675194205Z] Could not load necessary modules for Conntrack: Running modprobe nf_conntrack failed with message: `modprobe: WARNING: Module nf_conntrack not found in directory /lib/modules/5.15.77.1-1.cm2`, error: exit status 1
INFO[2022-12-02T23:37:25.675373210Z] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address
INFO[2022-12-02T23:37:25.682590505Z] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=moby
INFO[2022-12-02T23:37:25.682639206Z] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2022-12-02T23:37:25.682691108Z] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
WARN[2022-12-02T23:37:26.683350114Z] grpc: addrConn.createTransport failed to connect to {unix:///var/run/docker/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix:///var/run/docker/containerd/containerd.sock: timeout". Reconnecting...  module=grpc
failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: iptables v1.8.7 (legacy): Couldn't load target `MASQUERADE':No such file or directory
```

VM image details:
            "imageReference": {
                "publisher": "MicrosoftCBLMariner",
                "offer": "cbl-mariner",
                "sku": "cbl-mariner-2",
                "version": "latest",
                "exactVersion": "2.20221110.01"
            },

Moby details:
tdnf list installed | grep moby
moby-cli.x86_64                             20.10.12-4.cm2           @System
moby-containerd.x86_64                      1.6.6-3.cm2              @System
moby-engine.x86_64                          20.10.14-2.cm2           @System
moby-runc.x86_64                            1.1.2-4.cm2              @System

Am I missing anything?

**Comment by savaradh** [comment]
I was able to get it to work after commenting the following line in /lib/systemd/system/containerd.service
```
#ExecStartPre=/sbin/modprobe overlay
```
This was added yesterday to the WSL documentation - [Intro | Mariner OS (eng.ms)](https://eng.ms/docs/products/mariner-linux/gettingstarted/wsl)

However I had to do that for the VM as well. Something to note.

**Comment by eric-desrochers** [comment]
Comment the modprobe cmd is specific to WSL only. In a VM context, it is working out of the box.
@savaradh and I had a quick call and it is now working without modifying the containerd systemd service unit.
