### ISSUE TITLE
containerd.service doesn't start out of the box on WSL environment

### ISSUE THREAD

**Issue by eric-desrochers** [microsoft/CBL-Mariner#4368]
WSL2 doesn't support kernel modules shipped from Microsoft because the WSL utility doesn't have the ability to overlay modules into the WSL container filesystem

The above prevent a very common scenario under WSL where containerd won't start because of the following line:
https://github.com/microsoft/CBL-Mariner/blob/2.0/SPECS/moby-containerd/containerd.service#L7

I believe we can work around that by using ExecCondition= (tbd)

**Comment by eric-desrochers** [comment]
@mfrw for visibility.

**Comment by mfrw** [comment]
Marking this issue as resolved as it has been fixed internally.
