### ISSUE TITLE
Can I use conda in Mariner?

### ISSUE THREAD

**Issue by JiayuanL** [microsoft/CBL-Mariner#4397]
I downloaded [Mariner 1.0 x86_64 ISO](https://aka.ms/mariner-1.0-x86_64-iso). and created VM against the ISO. when I started the VM, seems conda is not installed, I could see conda here:https://github.com/microsoft/CBL-Mariner/tree/2.0/SPECS/conda, I suppose conda should be pre-installed, do I need to install the conda by myself? How could I start to use conda. Thanks!
![image](https://user-images.githubusercontent.com/49004334/206540715-2689291d-db60-4550-aede-2a97f10328df.png)

**Comment by eric-desrochers** [comment]
Do the following:

`$ sudo tdnf install conda -y`
