### ISSUE TITLE
[QUESTION] Advantages of Mariner on AKS

### ISSUE THREAD

**Issue by EvertonSA** [microsoft/CBL-Mariner#4414]
Hi, I came across lots of documentation on how to use Mariner on AKS, but haven't found much comparison on how better is it compared to default ubuntu (18.04 on aks 1.24 or 22.04 on aks 1.25). Ideally, I would like to know if it is worth testing it and how will this improve my cluster. 

from here https://microsoft.github.io/CBL-Mariner/docs/#key-capabilities-of-cbl-mariner-linux, I found some advantages, but I'm not an expert on Linux, so everything seems to be "normal stuff" to me. 

From Microsoft's perspective, why it was chosen to use Mariner instead of default ubuntu 22.04? Does it make nodes available more quicker? Does it support more containers? Does it fix any ubuntu know vulnerabilities? Does it provide more observability? Will it make my host count lower? These are a few questions that if answered in an article/research/marketing would make me fill excited to test.

At the moment, I don't have a good reason to try it but with research/articles/marketing, it would make me a little more curious if makes sense to me and the company I'm working on. 

And also, from existing users of Mariner on AKS, what are your thoughts? Does it worth it? How much better was it compared to default ubuntu images?

**Comment by 0xgrid** [comment]
Ubuntu is heavy with all of its additional packages installed on top of it. Why do you need multiple package managers like apt and snap and 3 network managers?

I was very interested in Mariner from the [readme.md](https://github.com/microsoft/CBL-Mariner#readme) 

I assume this is Microsoft's version of alpine

> CBL-Mariner has been engineered with the notion that a small common core set of packages can address the universal needs of first party cloud and edge services while allowing individual teams to layer additional packages on top of the common core to produce images for their workloads. This is made possible by a simple build system that enables:

>Package Generation: This produces the desired set of RPM packages from SPEC files and source files.
Image Generation: This produces the desired image artifacts like ISOs or VHDs from a given set of packages.
Whether deployed as a container or a container host, CBL-Mariner consumes limited disk and memory resources. The lightweight characteristics of CBL-Mariner also provides faster boot times and a minimal attack surface. By focusing the features in the core image to just what is needed for our internal cloud customers there are fewer services to load, and fewer attack vectors.

I recommend trying it out and seeing how its footprint in memory and CPU usage differs. 

![image](https://media4.giphy.com/media/IoP0PvbbSWGAM/giphy.gif?cid=ecf05e47uh8j2tmjd62lst0lpi7hsibzympefkaqjzt04x8f&rid=giphy.gif&ct=g)

**Comment by zcobol** [comment]
_Why do you need multiple package managers_ ...CBL-Mariner uses `tdnf` if `core` installation is selected. In `full` mode both `tdnf` and `dnf` are installed.

**Comment by EvertonSA** [comment]
Btw, a smaller attack surface is very attractive, I'm aware of the security improvements of Mariner in this topic. I want to know if there more to that!

**Comment by Tensibai** [comment]
> Ubuntu is heavy with all of its additional packages installed on top of it. Why do you need multiple package managers like apt and snap and 3 network managers?

snap goal is to install not validated packages totally out of band of the system and have no impact on it, not installed by default on server install of Ubuntu.
I really wonder what you're talking about with the 3 network managers, never had more than one in server install. 
Obviously if you're comparing a Desktop install including GUI with Mariner you'll have a very different footprint.

**Comment by jperrin** [comment]
To come back to the original question:

Both Mariner and Ubuntu are available. With Mariner we are offering more of an end-to-end solution designed for Azure and AKS. Customers will have the option to use the container host (Ubuntu or Mariner) they feel is right for them. You'll see features and more AKS specific improvements coming in the future as we continue our development and integration.
