### ISSUE TITLE
Download error when downloading kernel-headers-5.15.82.1-1.cm2.noarch.rpm

### ISSUE THREAD

**Issue by FeatherXavier** [microsoft/CBL-Mariner#4455]
HTTP returned 404 when downloading rpm flies.
Building on WSL2 Ubuntu 22.04.
 Here is the log:
      --2022-12-15 16:57:08--  https://packages.microsoft.com/cbl-mariner/2.0/prod/base/debuginfo/x86_64/kernel-headers-5.15.82.1-1.cm2.noarch.rpm
        Resolving packages.microsoft.com (packages.microsoft.com)... 40.83.79.38
        Connecting to packages.microsoft.com (packages.microsoft.com)|40.83.79.38|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2022-12-15 16:57:09 ERROR 404: Not Found.

        Downloading toolchain RPM: kernel-headers-5.15.82.1-1.cm2.noarch.rpm
        --2022-12-15 16:58:25--  https://packages.microsoft.com/cbl-mariner/2.0/prod/base/x86_64/kernel-headers-5.15.82.1-1.cm2.noarch.rpm
        Resolving packages.microsoft.com (packages.microsoft.com)... 23.99.120.248
        Connecting to packages.microsoft.com (packages.microsoft.com)|23.99.120.248|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2022-12-15 16:58:26 ERROR 404: Not Found.

        --2022-12-15 16:58:26--  https://packages.microsoft.com/cbl-mariner/2.0/prod/base/debuginfo/x86_64/kernel-headers-5.15.82.1-1.cm2.noarch.rpm
        Resolving packages.microsoft.com (packages.microsoft.com)... 23.99.120.248
        Connecting to packages.microsoft.com (packages.microsoft.com)|23.99.120.248|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2022-12-15 16:58:27 ERROR 404: Not Found.

**Comment by PawelWMS** [comment]
This package has not been published, yet. Please run your builds on top of official Mariner releases (the `2.0-stable` and `1.0-stable` point to the latest release for each of the Mariner versions), not directly from `main` or `1.0-dev`, as these are development branches.
