### ISSUE TITLE
Many Quirky Errors when Installing via Graphical Mode

### ISSUE THREAD

**Issue by 0xgrid** [microsoft/CBL-Mariner#4464]
Attempted install of mariner via ISO: https://osrelease.download.prss.microsoft.com/pr/download/Mariner-2.0-x86_64.iso with graphical interface and received a segfault.

![image](https://user-images.githubusercontent.com/4031468/208234025-f3cf51fc-378f-4b30-a17a-3323cd2df8ed.png)

Saw there was a logger in the output, tried to ls to look for any logs, however the whole right side of the keyboard seems to be disabled only in this OS and I could not type the L in ls

Was really excited to try a new lightweight OS to run my VMs. 

- [ ] Fix half keyboard not working
- [ ] Fix segfault with graphical install

![image](https://media1.giphy.com/media/ktcUyw6mBlMVa/giphy.gif?cid=ecf05e47l1j44wtbvjd80nzx11bxkk8ice50yhruz68nmz8x&rid=giphy.gif&ct=g)

**Comment by zcobol** [comment]
@0xgrid if the graphical installed doesn't work why are you throwing away the printer?

**Comment by MateuszMalisz** [comment]
Fixed in #4713
