### ISSUE TITLE
Cannot hear Audio through KVM/VNC installing Speech Mode

### ISSUE THREAD

**Issue by 0xgrid** [microsoft/CBL-Mariner#4465]
Was testing out the speech enabled install. Did not hear any audio. Unsure what the speech experience should be. Please advise what portions of the installer should expect audio in.

**Comment by 0xgrid** [comment]
![image](https://media4.giphy.com/media/9VcH46NJtByo4D25xZ/giphy.gif?cid=ecf05e47h5j6ip3fc52be6btgi0uj2ofjmo9itidm3h1pns0&rid=giphy.gif&ct=g)

**Comment by oliviacrain** [comment]
Thanks for the report! Text-to-speech should be enabled throughout the terminal-based UI when the speech-enabled install is enabled. Last time I tested, text-to-speech was working in QEMU, on bare-metal, and in VirtualBox for both 1.0 and 2.0.

Please let me know if you're using the 1.0 or 2.0 ISO, and I'll start working on a fix!

**Comment by 0xgrid** [comment]
Issue was with noVNC client
