### ISSUE TITLE
Kernel Panic when installing CBL-Mariner 2.0 on Dell R740 & R750 (Physical Hardware)

### ISSUE THREAD

**Issue by nsalant** [microsoft/CBL-Mariner#4485]
Is it possible to install CBL-Mariner 2.0 on physical hardware?
We've tried to do so (on Dell R740 & R750) and when installer tries to boot, we get an error "out of memory" followed by Kernel Panic message.
![CBL-Mariner20KernelPanic](https://user-images.githubusercontent.com/92673617/208887232-1193e3f2-93b2-4224-9869-953b684e0b0e.PNG)

**Comment by elsaco** [comment]
@nsalant CBL-Mariner does work on real hardware. I have it running on a Supermicro X10SRA using UEFI mode and no secure boot. Are you using any fake raid (a.k.a Intel RAID) on those Dells? It might help if you convert the drives to non-raid.

**Comment by nsalant** [comment]
Have no special configuration (no RAID, just SSD attached to USB).
Tried to boot CBL-Mariner 2.0 using virtual media (iDRAC) & disk on key.
Both failed immediately, the installer never loaded.
Can it be something with the default kernel?
Should I try to build the ISO using a different kernel version (like rt kernel)?

**Comment by elsaco** [comment]
Was CBL-Mariner already installed on the USB/SSD drive? Looks like it can't find some block device, see `Unable to mount root fs on unknown-block(1,0)` kernel message. You could use virtual media in iDRAC and boot the ISO. Do a new install or fix the existing one.

**Comment by nsalant** [comment]
USB (disk on key) has the CBL-Mariner 2.0 installation deployed on using Rufus,
SSD is clean (used diskpart --> clean to make sure).
Doesn't matter which one I use, Disk on key or virtual media - both with same result: Out of memory and Kernel panic.

**Comment by nsalant** [comment]
Succeeded to ue the kernel-rt instead of default one.
The Kernel Panic still occuring but with a little more detailed error:
<img width="1097" alt="kernel-rt" src="https://user-images.githubusercontent.com/92673617/209460821-a842100f-aacf-438c-8862-d6c8e4a51c18.PNG">

**Comment by nsalant** [comment]
Was a calamares package bug.
When creating iso without this package in installation, it was booting.
Fixed in [2.0.20230208-2.0](https://github.com/microsoft/CBL-Mariner/releases/tag/2.0.20230208-2.0)
