### ISSUE TITLE
Fail to replace Kernel version using instruction on CBL-MarinerTutorials repo (CBL-Mariner 2.0)

### ISSUE THREAD

**Issue by nsalant** [microsoft/CBL-Mariner#4490]
I'm trying to use the kernel-rt 5.15.55.1 instead of the default one (5.15.82) without success.
Following the instructions on [CBL-MarinerTutorials](https://github.com/microsoft/CBL-MarinerTutorials/blob/main/docs/kernel/modify_kernel.md).
Is it possible to use a different kernel such as rt kernel (from extended)?
As an alternate method, used the following procedure (all done on Ubuntu 20.04.5 adter running apt update & upgrade):
Cloned **~/CBL-Mariner/SPECS-EXTENDED/kernel-rt** to **~/CBL-MarinerTutorials/SPECS/kernel-rt**
Downloaded sources from **https://packages.microsoft.com/cbl-mariner/2.0/prod/extended/srpms/kernel-rt-5.15.55.1-2.cm2.src.rpm**
Extracted the **kernel-5.15.55.1.tar.gz** to **~/CBL-MarinerTutorials/SPECS/kernel-rt**
Verified all signatures match
Changed dir to **~/CBL-MarinerTutorials/toolkit**
Ran the command sudo **make iso CONFIG_FILE=../imageconfigs/demo_iso.json**
Seems like the kernel was compiled successfully but the ISO on the out directory still contains the default one (5.15.82)
Opened the **initrd** on the **boot** directory in the ISO to verify

**Comment by nsalant** [comment]
Same as before - I'm not referring to an installed system but building the ISO for deployment.
I can't install the compiled kernel binaries on an installation disk on key that was made from the ISO using Rufus.
I ran the compilation of the rt-kernel from sources and succeeded (got the kernel.../debug-info.../devel... rpms).
But now I need to inject it to the installation ISO while making it.
I'm a bit fuzzy about the process - is the toolkit from the main repo or the Tutorials repo responssible to which kernel to use when building?
And where is this implemented? (I can imagine it's one of the JSON files but I didn't find which)

**Comment by elsaco** [comment]
@nsalant if you want to use the default `kernel-rt`modify the build file and replace `kernel` with `kernel-rt`. This will build an image with the latest realtime kernel CBL-Mariner offers. Also, you need to add the `rt-packages.json` to the `PackageLists`. Here's a sample `full.json` I used to package the realtime kernel:

```
elsaco@think:~/GitHub/CBL-Mariner/toolkit$ cat imageconfigs/full.json 
{
    "SystemConfigs": [
        {
            "Name": "CBL-Mariner Full",
            "PackageLists": [
                "packagelists/developer-packages.json",
                "packagelists/virtualization-host-packages.json",
                "packagelists/core-packages-image.json",
                "packagelists/core-tools-packages.json",
                "packagelists/hyperv-packages.json",
                "packagelists/ssh-server.json",
                "packagelists/selinux-full.json",
                "packagelists/drtm.json",
		"packagelists/rt-packages.json"
            ],
            "KernelCommandLine": {
                "SELinux": "permissive"
            },
            "KernelOptions": {
                "default": "kernel-rt"
            }
        },
        {
            "Name": "CBL-Mariner Core",
            "PackageLists": [
                "packagelists/hyperv-packages.json",
                "packagelists/core-packages-image.json"
            ],
            "KernelOptions": {
                "default": "kernel-rt"
            }
        }
    ]
}
```
To build your own custom kernel just add a sanitized  `kernel.spec` to the `SPECS/kernel` folder.

This is the `kernel-rt` ISO running on KVM:
![cbl-mariner_kernel-rt](https://user-images.githubusercontent.com/3933920/209406436-f854b755-c396-4de2-838b-8f14d9e16cbe.png)

**Comment by nsalant** [comment]
@elsaco Thank you for your help!
Indeed when using this procedure I'm getting the RT kernel when the system is up after installation.
But the problem remains that the installation is booting the updated one and not the RT (5.15.82).
Seems like this procedure doesn't use the RT kernel in the installation.

**Comment by nsalant** [comment]
@elsaco Update: succeeded when changing all JSON files to kernel-rt.
Thank you very much for your help!
