### ISSUE TITLE
Unable to boot CBL-Mariner 2.0 from iPXE

### ISSUE THREAD

**Issue by klitkowx** [microsoft/CBL-Mariner#4527]
I'm trying to boot a CBL-Mariner 2.0 from iPXE but this system fails to boot. It fails on:
![image](https://user-images.githubusercontent.com/74708896/210350460-ac9f059b-caa7-4be4-8bcc-70c7f2792a21.png)

Could someone pass here a working iPXE script? My iPXE script:
kernel nfs://{{nfs_ip}}/{{path}}/boot/vmlinuz
initrd nfs://{{nfs_ip}}/{{path}}/boot/initrd.img
imgargs vmlinuz initrd=initrd.img root={{nfs_ip}}:/{{path}},nfsvers=3 selinux=0 intel_iommu=on net.ifnames=0 biosdevname=0 BOOTIF={mac} ip={ip}::{gateway}:{netmask}::eth0:none rw
boot

Also, it fails to boot from iSCSI:
#!ipxe

sanboot iscsi:{ip-addr}::::iqn.2021-01.diskless:${hostname}-ib-lnx..CBL20-082942 ||
sanboot iscsi:{ip-addr}::::iqn.2021-01.com.diskless:${hostname}-ib-lnx..CBL20-082942

**Comment by elsaco** [comment]
For me after iPXE boot the installer is trying to mount an ISO. Here's a screenshot for reference:

![cbl-mariner_ipxe_error](https://user-images.githubusercontent.com/3933920/211467323-ad858f5d-a5e8-46e6-b64e-13bce395cd03.png)

The command line is `BOOT_IMAGE=/isolinux/vmlinuz root=/dev/ram0 logleve=3 mariner.media=CDROM lockdown=integrity sysctl.kernel.unprivileged_bpf_disabled=1` and `mariner.media` seems to be the issue.

For iPXE `http` is used to transfer files, but `nfs` should work also.

**Comment by klitkowx** [comment]
I'm not trying to boot the installer but already installed the system from iPXE. The system was installed on the HDD and then migrated to the zfs to allow iPXE boot from our host.

**Comment by henryli001** [comment]
@klitkowx based on the terminal log, seems like the installer fails to recognize that this is a PXE boot scenario. The installer will check whether "--image-config=<path to image config.json on PXE server>" appears in /proc/cmdline to determine if this is a PXE boot scenario or not. Here's the code reference: https://github.com/microsoft/CBL-Mariner/blob/c39cab1a9e9705c68f0e1e7e1a53fd7a97de6fe6/toolkit/resources/imageconfigs/additionalfiles/iso_initrd/root/runliveinstaller#L56. 

Therefore, please specify "--image-config" in your PXE configuration on the PXE server side and that ought to trigger the PXE boot condition within the installer.
