### ISSUE TITLE
How can I enable systemd in WSL 2 system distro?

### ISSUE THREAD

**Issue by aki-k** [microsoft/CBL-Mariner#4529]
I have a problem with WSL 2. If I start it from Windows task scheduler, weston in the WSL 2 system distro
starts crashing once per second [WSL Github issue report](https://github.com/microsoft/wslg/issues/564)

 I tested with

    C:\>wsl --system
    # chmod 000 /usr/bin/weston

and that helped with weston crashing. But the change was erased during Windows boot.

So is there some way to run scheduled jobs in the WSL 2 system distro which is CBL Mariner?

**Comment by elsaco** [comment]
What is called the `system` distro in WSL it's a read only container that provides audio and graphics services to other WSL containers, distros that a  user actually uses. You can enable `systemd` on a WSL distro by adding `systemd = enabled` to `/etc/wsl.conf`

**Comment by aki-k** [comment]
I'm having strange problems with programs running in WSL 2 and I'd like to get rid of weston crashing in
the system distro. Is there any way I could do it?

**Comment by rokejulianlockhart** [comment]
@aki-k, this isn't the place to ask such questions.

**Comment by aki-k** [comment]
Ok weston isn't crashing any more with WSL 2
