### ISSUE TITLE
Package microsoft/git for Mariner

### ISSUE THREAD

**Issue by markphip** [microsoft/CBL-Mariner#4665]
I am trying to install the microsoft/git fork on Mariner. I am currently doing so by extracting the .deb package they provide. This fails at runtime with this error:

```
/usr/local/lib/git-core/git-remote-https: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
```

It looks like curl must be built differently on Debian/Ubuntu. Is there a package for Mariner maintained anywhere. I am not 100% certain anyone actually needs this. I was working on this in preparation to support more teams using Mariner in Codespaces, but I am not certain if there is any overlap between teams that need Mariner and teams that have large monorepo and need the GVFS support. Just wondering if there are any options.

**Comment by mfrw** [comment]
Would building from source be an option ?

**Comment by markphip** [comment]
I started to look at that yesterday. What is the best way to get the right devtool dependencies installed so I can build from source? I did not see a `git-devel` package and then was not sure what the name of the meta package is to get the C compiler and tools etc.

I guess the fact that a package does not already exist may be a good sign for me that it no one wants it

**Comment by elsaco** [comment]
`scalar` was added to `git v2.38` release. CBL-Mariner provides `git v2.33.4` so an upgrade is needed. The source from `microsoft/git` builds okay on CBL-Mariner. `openss-devel` and `gettext` are needed, if not installed already. Here's version output after building from source:

```
mariner% ./scalar version
git version 2.39.1.vfs.0.0

mariner% ./git version
git version 2.39.1.vfs.0.0
```

Another option is downloading a Fedora RPM which is much closer to CBL-Mariner. A DEB package won't play nice on CBL-Mariner.

**Comment by markphip** [comment]
I am specifically looking for the fork due to the support for GVFS which has not been upstreamed.

I am fine with pursuing my own build. I've looked through docs, but not finding the name of the package that will get me the C compilers and build tools? I was also originally thinking I would install the OSS `git-devel` package assuming that would pull in all the dependencies needed to build Git but did not see that either. I am using `mcr.microsoft.com/cbl-mariner/base/core:2.0` as my base image

**Comment by oliviacrain** [comment]
The `build-essential` package is a catch-all development package for C/C++. That'll get you all of the packages listed as requirements in the `build-essential` [spec file].

Our `*-devel` packages typically contain files that are used to build against that a given package's libraries (e.g. unversioned shared libraries, pkgconfig files, etc.), but don't pull in the full closure of build requirements. If you install `dnf` and `dnf-plugins-core`, you can use the [`dnf builddep` command](https://dnf-plugins-core.readthedocs.io/en/latest/builddep.html) to automate installation of the dependencies needed to build a package.

[spec file]: https://github.com/microsoft/CBL-Mariner/blob/main/SPECS/build-essential/build-essential.spec

**Comment by markphip** [comment]
Thanks, it has been a while I guess because I had been trying to install `build-essentials` 🤦 

I will close the issue.
