### ISSUE TITLE
update-grub and grub2-mkconfig commands not found

### ISSUE THREAD

**Issue by arbitrarymahi** [microsoft/CBL-Mariner#4701]
I need to update the /etc/default/grub file in marinerOS but it seems it is missing. There is an open issue regarding that as well https://github.com/microsoft/CBL-Mariner/issues/2237

I also tried `update-grub` and `grub-mkconfig` commands but they are also not found. 

**sudo: update-grub: command not found**

**sudo: grub2-mkconfig: command not found**

There is /boot/grub2/grub.cfg file present in the OS though so not sure if it's the issue with grub package or something else. 

I am using ISO_2.0  from the repository dl link. https://aka.ms/mariner-2.0-x86_64-iso

**Comment by oliviacrain** [comment]
With the caveat that I don't know much about this area- it looks like the `grub2` package should contain `/sbin/grub2-mkconfig`.

**Comment by arbitrarymahi** [comment]
I have found a fix to the problem. Actually it is missing thepackages which contain `grub-mkconfig`
In my case installing the following resolved the error:

`dnf install grub2-efi grub2-efi-modules shim`

after that if update-grub is not found you can manually create the .sh file accordingly.

Hope it helps :)
