### ISSUE TITLE
Support of Linux Kernel 6.1 (LTS) in Mariner

### ISSUE THREAD

**Issue by ohault** [microsoft/CBL-Mariner#4872]

**Comment by jslobodzian** [comment]
acknowledged.  Thank you for your suggestion.

**Comment by ohault** [comment]
Hi @jslobodzian, can you please re-open this has yet to be done ?

**Comment by ohault** [comment]
What is the status update about this work?

**Comment by ohault** [comment]
Meanwhile this ticket was closed improperly by 4th March, the first 6.1 tag https://github.com/microsoft/CBL-Mariner-Linux-Kernel/releases/tag/rolling-lts%2Fmariner-3%2F6.1.20.1 only appears by 5th, May.
