### ISSUE TITLE
zlib v1.2.12 causes java.util.zip.ZipException,update to Version 1.2.13

### ISSUE THREAD

**Issue by surendarraj** [microsoft/CBL-Mariner#5391]
zlib v1.2.12 fails CRC check as illustrated in  [https://github.com/oracle/graal/issues/4479](url)
more details in [https://github.com/madler/zlib/issues/613](url)

To reproduce : 

yum install git
git clone https://github.com/alexarchambault/arch-linux-native-image-crc32-issue.git
cd arch-linux-native-image-crc32-issue/

root [ /arch-linux-native-image-crc32-issue ]# rpm -qi zlib
Name        : zlib
Version     : 1.2.12
Release     : 2.cm2
Architecture: x86_64
Install Date: Fri 07 Apr 2023 04:35:29 PM UTC
Group       : Applications/System
Size        : 104189
License     : zlib
Signature   : RSA/SHA256, Thu 25 Aug 2022 07:10:36 PM UTC, Key ID 0cd9fed33135ce90
Source RPM  : zlib-1.2.12-2.cm2.src.rpm
Build Date  : Wed 24 Aug 2022 10:09:40 PM UTC
Build Host  : b66f8292c000000.k540vtm2vyvehe1hsen1lrqk3g.bx.internal.cloudapp.net
Vendor      : Microsoft Corporation
URL         : https://www.zlib.net/
Summary     : Compression and decompression routines
Description :
Compression and decompression routines

root [ /arch-linux-native-image-crc32-issue ]# ./compute-crc32 MANIFEST.MF
**CRC32: 6318fb**
root [ /arch-linux-native-image-crc32-issue ]# ./compute-crc32 MANIFEST.MF "$(cat splits)"
Using splits: 512,1024,1320,1832,2344,2856,3368,3880,4392,4904,5416,5766,6278,6790,7302,7814,8326,8838,9093,9605,10117,10629,11141,11653,12165,12677,13189,13559,14071,14583,15095,15607,16119,16631,17143,17655,18052,18564,19076,19588,20100,20612,21124,21636,21952,22464,22976,23488,24000,24512,25024,25536,26048,26560,27072,27584,27619,28131,28643,29155,29667,30179,30691,31203,31715,32227,32739,33251,33694,34206,34718,35230
**CRC32: 49656e6**

it should return same CRC value as in rhel,ubuntu systems 

[root@iumtest11 arch-linux-native-image-crc32-issue]# ./compute-crc32 MANIFEST.MF
**CRC32: 6318fb**
[root@iumtest11 arch-linux-native-image-crc32-issue]# ./compute-crc32 MANIFEST.MF "$(cat splits)"
Using splits: 512,1024,1320,1832,2344,2856,3368,3880,4392,4904,5416,5766,6278,6790,7302,7814,8326,8838,9093,9605,10117,10629,11141,11653,12165,12677,13189,13559,14071,14583,15095,15607,16119,16631,17143,17655,18052,18564,19076,19588,20100,20612,21124,21636,21952,22464,22976,23488,24000,24512,25024,25536,26048,26560,27072,27584,27619,28131,28643,29155,29667,30179,30691,31203,31715,32227,32739,33251,33694,34206,34718,35230
**CRC32: 6318fb**

please see [https://www.zlib.net/](url) Version 1.2.13 key Updates for fix done related to CRC which was broken in Version 1.2.12.

**Comment by mfrw** [comment]
Thanks for pointing this out @surendarraj. We will upgrade to 1.2.13

**Comment by mfrw** [comment]
zlib upgrade merged to main
