### ISSUE TITLE
git clone link referenced to the wrong one

### ISSUE THREAD

**Issue by patrick330602** [microsoft/CBL-Mariner#567]
In here: https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/quick_start/quickstart.md#clone-cbl-mariner

It uses the SSH method to clone, which will cause normal users to not able to clone due to lack of permissions. HTTPS should be used for the repository.

**Comment by christopherco** [comment]
@patrick330602 Thanks for reporting this! I have made the appropriate quickstart doc changes.
