### ISSUE TITLE
Create link for publicly available ISO Image

### ISSUE THREAD

**Issue by pranavnt** [microsoft/CBL-Mariner#577]
I wanted to try playing around with CBL-Mariner on a VM, and it would be a lot easier to set up if there is a link to a publicly available ISO image. If it would be possible to host an ISO image online, it would be great! Thanks for all the awesome work that you do!!

**Comment by jslobodzian** [comment]
ISO images are now available.  See README.md file for link and instructions.

**Comment by pranavnt** [comment]
Thank you @jslobodzian!!
