### ISSUE TITLE
Upgrade gcc to 12.2.1

### ISSUE THREAD

**Issue by saranyareddy24** [microsoft/CBL-Mariner#5915]
Hi,

Is it possible to upgrade gcc package to 12.2.1 or should we create another spec file for 12.2.1 if we have to support 12.2.1 version as well?

**Comment by mfrw** [comment]
There is a WIP PR for adding `gcc12`.
- https://github.com/microsoft/CBL-Mariner/pull/5799

/cc @anphel31

**Comment by saranyareddy24** [comment]
Thanks @mfrw
