### ISSUE TITLE
setfacl not found in quickstart build on Ubuntu

### ISSUE THREAD

**Issue by awolman** [microsoft/CBL-Mariner#6013]
I am following the build instructions in the Quick Start guide here:
https://github.com/microsoft/CBL-Mariner/blob/2.0/toolkit/docs/quick_start/quickstart.md

When I build with the following command:
sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json

I get an error output:
make: setfacl: No such file or directory

This occurs because toolkit/scripts/utils.mk uses the setfacl utility, but it is not installed by default on Ubuntu.

If installing the acl package is a requirement, then it should be listed on the build prerequisites page here:

https://github.com/microsoft/CBL-Mariner/blob/2.0/toolkit/docs/building/prerequisites-ubuntu.md

**Comment by mfrw** [comment]
Thank you @awolman for your feedback. We should add `acl` package as a requirement for `ubuntu` & mariner both.

**Comment by mfrw** [comment]
Closing as docs updated in `main` via:
- #6020
