### ISSUE TITLE
SSHFS

### ISSUE THREAD

**Issue by AngeloBestetti** [microsoft/CBL-Mariner#6048]
I´m trying to install sshfs but no luck.

dnf install sshfs
Error: Unable to find a match: sshfs

dnf install sshfs-fuse
Error: Unable to find a match: sshfs-fuse

How can I install on Mariner?

**Comment by mfrw** [comment]
`fuse-sshfs` is provided by the `Extended Repository`.

Please try this:
```bash
sudo tdnf install mariner-repos-extended
sudo tdnf update
sudo tdnf install fuse-sshfs
```

**Comment by AngeloBestetti** [comment]
100% perfect, thank´s a lot
