### ISSUE TITLE
how to update Mariner in AKS agent-pool for security patches

### ISSUE THREAD

**Issue by lesscodingmorehappiness** [microsoft/CBL-Mariner#6059]
Hi,

We are using Mariner in our AKS agent pool vms. We received some vulnerability alarms and need to get latest security patches for these Mariner vms. But there seems no way to directly login/connect and interact with AKS agent pool machines so we can't use RPM to download security patches on the machines.

How can we get security patches and fix vulnerability issue in this case? Do we have to recreate agentpool for AKS?

Thanks

**Comment by mfrw** [comment]
I think, this question would be better suited at the internal Mariner-AKS channels.
This may not be the right place for this question.
/cc @christopherco, @hbeberman
