### ISSUE TITLE
GitHub bot to label issues automatically

### ISSUE THREAD

**Issue by lpereira** [microsoft/CBL-Mariner#62]
Would be nice if we had a GitHub bot to label issues automatically:

- If `CVE-\d+-\d+` is mentioned in the commit message, newly-added changelog entry of a spec file, etc, add a `Security` label
- If a file named `CVE-\d+-\d+\.patch` is added to a spec directory, add a `Security` label
- If the PR touches spec files or files in a spec directory, add a `Package` label
- If the PR touches files related to tools, add a `Tooling` label
- If the PR touches files related to CI, add a `CI` label

This should help prioritize stuff better.

**Comment by JamieMagee** [comment]
@cliffkoh I think you're the correct person to ask here?

**Comment by cliffkoh** [comment]
Yes, I can help. Fabric Bot (aka msftbot) can help with all of these. https://aka.ms/fabricbotdocs to get started.

**Comment by lpereira** [comment]
Went through the video material, and this looks great! I've already applied to onboard this repository there.

**Comment by lpereira** [comment]
Bot has been set up for this repo.  It's a simple configuration, only matching the rules I mentioned, but looking over some of the example configurations, it's possible to do a whole lot more. Let's just start simple and go from there. Thanks!
