### ISSUE TITLE
compiler-rt is not working with CLANG/LLVM-16 version

### ISSUE THREAD

**Issue by navjotsinghji** [microsoft/CBL-Mariner#6269]
Mariner is supporting both CLANG and LLVM versions 12 as well as 16, but compiler-rt is not built with LLVM-16. It's still referencing llvm-12, so we are having build failures when we try to install clang16, llvm16 and compiler-rt
 

[CBL-Mariner/SPECS/llvm/llvm16.spec at 2.0 · microsoft/CBL-Mariner (github.com)](https://github.com/microsoft/CBL-Mariner/blob/2.0/SPECS/llvm/llvm16.spec)

[CBL-Mariner/SPECS/compiler-rt/compiler-rt.spec at 2.0 · microsoft/CBL-Mariner (github.com)](https://github.com/microsoft/CBL-Mariner/blob/2.0/SPECS/compiler-rt/compiler-rt.spec)

 A short snippet of our build error. This is because compiler-rt tries to install llvm, but llvm16 is installed and there are conflicts.

_Found 61 problems
file /usr/bin/bugpoint from install of llvm-12.0.1-7.cm2.x86_64 conflicts with file from package llvm16-16.0.0-3.cm2.x86_64
file /usr/bin/dsymutil from install of llvm-12.0.1-7.cm2.x86_64 conflicts with file from package llvm16-16.0.0-3.cm2.x86_64_

**Comment by berlin-with0ut-return** [comment]
hey, have you been able to find any resolution for this issue?

**Comment by jslobodzian** [comment]
We're not fully supporting this in Mariner 2.0.  However, we are upgrading clang for Azure Linux 3.0.  This work is in progress
