### ISSUE TITLE
golang package GOROOT_FINAL seems incorrect

### ISSUE THREAD

**Issue by cpuguy83** [microsoft/CBL-Mariner#6363]
In https://github.com/microsoft/CBL-Mariner/blob/ae993d0b3288b1bb291f5f468169fa36b681b4d4/SPECS/golang/golang.spec#L82

It seems to be setting `GOROOT` to `/usr/bin/go`.
But `/usr/bin/go` is a binary.
Actual `GOROOT` should be `/usr/lib/golang` in this case.

I found this while trying to build packages that depend on go using the mariner toolkit.
For whatever reason in the chroot during package build /etc/profile is not being sourced so GOROOT (and other GO* vars) are left unset leaving them to the compiled-in versions.
This yields a somewhat cryptic error (or at least very unexpected) like: `go: cannot find GOROOT directory: /usr/bin/go`

**Comment by cpuguy83** [comment]
Relevant for go1.21: https://github.com/golang/go/issues/62047

**Comment by sozercan** [comment]
cc @jslobodzian

**Comment by mfrw** [comment]
Fixed as per upgrade to go1.21.6
