### ISSUE TITLE
Rabbitmq Image Failed:  OCI runtime create failed: permission denied

### ISSUE THREAD

**Issue by sukhbir-singh** [microsoft/CBL-Mariner#6563]
I am getting this error when trying to run container image of rabbit mq. Please help in fixing this as soon as possible.

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/rabbitmq-server-docker-entrypoint.sh": permission denied: unknown.

https://mcr.microsoft.com/en-us/product/cbl-mariner/base/rabbitmq-server/about

Command that I am trying to run: 
docker run -d --hostname my-rabbit --name some-rabbit mcr.microsoft.com/cbl-mariner/base/rabbitmq-server:3

**Comment by christopherco** [comment]
I see similar behavior - Tagging @sameluch who may have more insight on this rabbitmq container composition

**Comment by sameluch** [comment]
@sukhbir-singh I have made some updates on our build side that will solve this issue in the next release of the container.
