### ISSUE TITLE
The package kubernetes-1.28.3-1.cm2 lost its version information during the build.

### ISSUE THREAD

**Issue by jing8956** [microsoft/CBL-Mariner#6719]
**Describe the bug**
The current latest version (1.28.3.1.cm2) of the Kubernetes package has lost the major and minor version information during compilation, so kubeadm and kubectl will not work when executing version-related commands.

**To Reproduce**
1. Install or update kubernetes-kubeadm-1.28.3.1.cm2 and kubernetes-client-1.28.3.1.cm2.
    `sudo tdnf install kubernetes-kubeadm-1.28.3.1.cm2 kubernetes-client-1.28.3.1.cm2`
2. Execute the command to display the version.
    `sudo kubeadm version`
    `sudo kubectl version`
3. The console will display the following results.
    ```
    kubeadm version: &version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+a8a1abc25cad87333840cd7d54be2efaf31a3177", GitCommit:"a8a1abc25cad87333840cd7d54be2efaf31a3177", GitTreeState:"", BuildDate:"2023-11-06T18:03:38Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
    ```
    ````
    Client Version: v0.0.0-master+a8a1abc25cad87333840cd7d54be2efaf31a3177
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    The connection to the server localhost:8080 was refused - did you specify the right host or port?
    ````
4. Execute commands related to the version.
    `sudo kubeadm init --dry-run`
5. The console will display the following results.
    ```
    I1110 04:39:14.280165    6558 version.go:256] remote version is much newer: v1.28.3; falling back to: stable-0.0
    version "stable-0.0" doesn't match patterns for neither semantic version nor labels (stable, latest, ...)
    To see the stack trace of this error execute with --v=5 or higher
    ```

OS Version: 2.0.20231106

**Expected behavior**
When executing the kubexxx version command, it should display the correct version information, as they depend on this to work.

**Comment by mfrw** [comment]
Thank you @jing8956 for bringing this to our notice. We will look into it.

**Comment by mfrw** [comment]
Fix merged to `main`:
- #6722
