### ISSUE TITLE
Suggest releasing Kubernetes 1.27.X

### ISSUE THREAD

**Issue by jing8956** [microsoft/CBL-Mariner#6720]
**Is your feature request related to a problem? Please describe.**
Kubernetes is designed not to support updates across multiple minor versions. 
The latest version before the current 1.28.3-1.cm2 release was 1.26.3-4.cm2. 
If the decision is made to skip the release of version 1.27.X, these Kubernetes clusters created with kubeadm will not be able to upgrade via kubeadm, unless an external package source is introduced to install Kubernetes 1.27.X.

**Describe the solution you'd like**
Publish Kubernetes 1.27.X

**Describe alternatives you've considered**
Install and upgrade Kubernetes 1.27.X from an external package source.

**Comment by oaljoundi** [comment]
Hi @jing8956, I would suggest submitting this as a request on the AKS team: https://github.com/Azure/AKS/issues. The cbl-mariner GitHub is for Mariner (Azure Linux) requests exclusively.
