### ISSUE TITLE
New contributor PR questions

### ISSUE THREAD

**Issue by cwyborny** [microsoft/CBL-Mariner#6724]
In the contributor guidelines it says to do PR's against main branch, not #.0-stable.  I'm preparing a PR and cannot build against main because the kernel-headers-5.15.137.1-1 package isn't available.  I know some branches are not intended to always be buildable.  Is the documentation outdated?  For a PR for 2.0-stable, which branch should I do the PR for?

**Comment by mfrw** [comment]
Hi @cwyborny, the documentation is correct;

`2.0-stable` is a tag which always points to our latest stable release, what I think, you meant was the `2.0` branch.

We treat our `main` branch as a staging branch for `2.0`. We do not directly target our PRs to `2.0`.

> For a PR for ~2.0-stable~ 2.0, which branch should I do the PR for?

We should target the `main` branch. `main` gets merged to `2.0` and eventually once we release, it will be reflected in the `2.0-stable` tag.

**Comment by dmcilvaney** [comment]
For building on main branch, the reason it's failing is we don't guarantee those pacakges are published to our repos yet. Add `QUICK_REBUILD_TOOLCHAIN=y` to your build command (its a short-hand that turns on a bunch of rebuild options). We have more details in our docs here if you want the hows/whys: https://github.com/microsoft/CBL-Mariner/blob/2.0/toolkit/docs/building/building.md

**Comment by cwyborny** [comment]
Thanks, I may have used the wrong terminology, but building against main in preparation for a PR for Mariner 2.0 is what I'm trying to accomplish.  Thanks for the advice, will try the QUICK_REBUILD_TOOLCHAIN=y to try and check my build before submission.

**Comment by mfrw** [comment]
@cwyborny closing this issue as complete.
Please feel free to re-open if you face any other challenges.
