### ISSUE TITLE
Add CONFIG_ARM_SMMU{,_V3} to aarch64 kernel config

### ISSUE THREAD

**Issue by ddaney-fungible** [microsoft/CBL-Mariner#6818]
**Is your feature request related to a problem? Please describe.**
In order to use VFIO for userspace access to PCI functions, we need the IOMMU enabled. Also, IOMMU probably adds some safety to the system by blocking errant PCI DMA accesses.

**Describe the solution you'd like**
Add CONFIG_ARM_SMMU and CONFIG_ARM_SMMU_V3 to the aarch64 kernel config.

**Describe alternatives you've considered**
Use Ubuntu or Fedora instead of Mariner.

**Additional context**

**Comment by christopherco** [comment]
Thanks @ddaney-fungible for the feature request and PR!

Tagging @rlmenge and @htaubenfeld for awareness.

**Comment by christopherco** [comment]
Change to add the configs was merged and will be available in our next monthly package update. Thanks again for making the feature request and submitting a PR to add architectural IOMMU support for our ARM64 kernel
