### ISSUE TITLE
Unexpected node-problem-detector version

### ISSUE THREAD

**Issue by MF1-MS** [microsoft/CBL-Mariner#6839]
I have a VM with the 2.0.20231004 CBL-Mariner/Linux image. I can see from the [checked in spec](https://github.com/microsoft/CBL-Mariner/blob/2.0.20231004-2.0/SPECS/node-problem-detector/node-problem-detector.spec) that I was expecting node-problem-exporter to be 0.8.10-15.

```
sh-5.1# cat /etc/os-release
NAME="Common Base Linux Mariner"
VERSION="2.0.20231004"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"
```

However examining the box showed it to only have 0.8.8-1 installed, requiring me to manually update the package to quash a security alert.

```
sh-5.1# rpm -q node-problem-detector
node-problem-detector-0.8.8-1.cm1.x86_64
```

What's the source of this discrepancy?

**Comment by elsaco** [comment]
@MF1-MS when did you first install `node-problem-detector`? `cm1` in the release string implies `CBL-Mariner version 1`. The latest version is built from `node-problem-detector-0.8.10-17.cm2.src.rpm`.

**Comment by MF1-MS** [comment]
This was deployed using AKS in Azure. I did not explicitly install node-problem-detector, it's a package delivered on the image. The node image was updated since original deployment, and I would have expected the packages to reflect the current image version?

**Comment by christopherco** [comment]
@MF1-MS This `node-problem-detector` package is actually delivered through an AKS VM Extension. A new version of the extension is being worked on and deployed by AKS to remediate both the `.cm1` problem and also bring in the newer `node-problem-detector` which should squash the security alert.

**Comment by christopherco** [comment]
Was informed the updated AKS VM Extension should be rolled out, which should handle this issue.
