### ISSUE TITLE
Remove hidepid=2 default setting from /proc mount option

### ISSUE THREAD

**Issue by christopherco** [microsoft/CBL-Mariner#6922]
**Describe the bug**
Currently our images set `/proc` mount option with `hidepid=2` in `/etc/fstab`. The `hidepid` option prevents process IDs from being visible to all users. We introduced this as a security hardening setting for early targeted use-cases. However, as our distro has expanded in scope and usage, this setting has become a common compat issue for applications and system services, which heavily outweigh its proposed "security benefit".

Any user or service who wishes to utilize this setting for further PID protection can set the value as a post image configuration step.

**Expected behavior**
For Azure Linux 3.0, remove `hidepid=2` setting from /etc/fstab and remove the ability for our tools to configure `hidepid=2` by default.

**Comment by christopherco** [comment]
Additional references for moving away from `hidepid=2`:
- https://access.redhat.com/solutions/6704531
- https://security.stackexchange.com/questions/259134/why-is-the-mount-option-hidepid-2-not-used-by-default-is-there-a-danger-in-us

**Comment by rlmenge** [comment]
For further context, here is the original PR which added hidepid: https://github.com/microsoft/CBL-Mariner/pull/797 . This was added in relation to a bug [here](https://microsoft.visualstudio.com/OS/_workitems/edit/31858389). As noted above, there is an ability to turn this off in imageconfigs today by setting `HidepidDisabled` to `false`. However, this is not the default. 

After reading through the above references, I agree that the security benefits of hidepid (outlined in this [linux-audit article](https://linux-audit.com/linux-system-hardening-adding-hidepid-to-proc/) are not worth the broken functionality, and can be potentially avoided "via systemd's D-Bus interface"([RedHat solution 6704531](https://access.redhat.com/solutions/6704531)) although I have not tested this myself.

**Comment by christopherco** [comment]
Merged into 3.0 development branch. Closing
