### ISSUE TITLE
Is there a way to install 32 bit version of the glibc on 64 bit Mariner systems? 

### ISSUE THREAD

**Issue by AyushSingh-c** [microsoft/CBL-Mariner#7011]
Similar to libc6-i386(for debian)/ glibc.i686(for rhel)/ glibc-32bit(for openSUSE) is there a package to provide the shared libraries, development headers, and object files needed to compile and link 32 bit programs on 64 bit platforms in Mariner systems?

**Comment by mfrw** [comment]
AzureLinux does not support 32 bit architectures.
/cc @christopherco @jslobodzian

**Comment by christopherco** [comment]
@mfrw is correct. We currently only build and supply packages for supporting x86_64 and ARM64 architectures.

**Comment by jperrin** [comment]
I'm going to close to close this as "wontfix" for now as this won't be added in the 2.0 timeframe. if there's a justification to support this in future versions, we can consider it. Since many distros are trying to reduce 32bit support, it would take a pretty significant justification though.
