### ISSUE TITLE
Where to find the lksctp package for Mariner OS? 

### ISSUE THREAD

**Issue by westlaker** [microsoft/CBL-Mariner#7131]
Hi,

We need to have lksctp-dev or lksctp-tools to support our application development on Mariner OS. Would you please help me how to install that packages as I have failed to find them.

Thanks

**Comment by mfrw** [comment]
AzureLinux core does not ship with `lksctp-tools`, but the `EXTENDED Repository` does.

```bash
tdnf install mariner-repos-extended.noarch 

tdnf install lksctp-tools
```

NOTE: The packages shipped by extended repository are experimental and we do not recommend using them for production. They can be used for prototyping purposes.

![image](https://github.com/microsoft/CBL-Mariner/assets/4929861/97d655c2-55ea-4025-89fc-55804ba801c3)

**Comment by mfrw** [comment]
Please feel free to reopen if there are any further questions.
