### ISSUE TITLE
bcc-tools is not working with CLANG/LLVM-16 version

### ISSUE THREAD

**Issue by navjotsinghji** [microsoft/CBL-Mariner#7360]
Mariner is supporting both CLANG and LLVM versions 12 as well as 16, but bcc-tools is not built with LLVM-16. It's still referencing llvm-12, so we are having build failures when we try to install clang16, llvm16 and bcc-tools

[CBL-Mariner/SPECS/llvm/llvm16.spec at 2.0 · microsoft/CBL-Mariner (github.com)](https://github.com/microsoft/CBL-Mariner/blob/2.0/SPECS/llvm/llvm16.spec)

https://github.com/microsoft/CBL-Mariner/blob/3798a92d85758462fd12f7fa8abce93802de6234/SPECS/bcc/bcc.spec

**Comment by jslobodzian** [comment]
We're not fully supporting this in Mariner 2.0. However, we are upgrading clang for Azure Linux 3.0. This work is in progress
