### ISSUE TITLE
CHROOT environment lacking

### ISSUE THREAD

**Issue by fozog** [microsoft/CBL-Mariner#863]
I bump into 
ERRO[0000] env variable CHROOT_DIR not defined
Trying to workaround, the tool complains it does not find a chroot environment and a chroot-pool.lock file

**Comment by PawelWMS** [comment]
Hey, thanks for letting us know! Could you provide repro steps to hit this issue? And does your system satisfy all of the [build prerequisites](https://github.com/microsoft/CBL-Mariner/blob/1.0/toolkit/docs/building/prerequisites.md)?

**Comment by fozog** [comment]
I am using Ubuntu 20.04 as this is the only one available on my build system (Ampere Mount Snow).
prerequisite seem OK (Go 1.15.8, full python instead of python-minimal which is not available on 20.04).

 sudo make clean
Makefile:13: CONFIG_FILE is empty, defaulting to toolkit's core-efi.json unless CONFIG_FILE="" was set explicitly.
rm -rf /home/ff/CBL-Mariner/build/make_status
rm -rf /home/ff/CBL-Mariner/build/toolchain
rm -rf /home/ff/CBL-Mariner/build/toolchain_temp
rm -rf /home/ff/CBL-Mariner/build/logs/toolchain
rm -rf /home/ff/CBL-Mariner/build/make_status/toolchain_local_temp.flag
rm -f /home/ff/CBL-Mariner/toolkit/scripts/toolchain/container/toolchain-local-wget-list
rm -f /home/ff/CBL-Mariner/toolkit/scripts/toolchain/container/texinfo-perl-fix.patch
rm -f /home/ff/CBL-Mariner/toolkit/scripts/toolchain/container/Awt_build_headless_only.patch
rm -f /home/ff/CBL-Mariner/toolkit/scripts/toolchain/container/check-system-ca-certs.patch
rm -f /home/ff/CBL-Mariner/toolkit/scripts/toolchain/container/.bashrc
rm -rf /home/ff/CBL-Mariner/toolkit/out/tools
rm -rf /home/ff/CBL-Mariner/build/tools
rm -f /home/ff/CBL-Mariner/build/worker/worker_chroot.tar.gz
Verifying no mountpoints present in /home/ff/CBL-Mariner/build/worker/
/home/ff/CBL-Mariner/toolkit/scripts/safeunmount.sh "/home/ff/CBL-Mariner/build/worker/" && \
/home/ff/CBL-Mariner/toolkit/scripts/safeunmount.sh "/home/ff/CBL-Mariner/build/validatechroot/" && \
rm -rf /home/ff/CBL-Mariner/build/worker && \
rm -rf /home/ff/CBL-Mariner/build/validatechroot
find: ‘/home/ff/CBL-Mariner/build/validatechroot/’: No such file or directory
rm -rf /home/ff/CBL-Mariner/build/macros
rm -rf /home/ff/CBL-Mariner/build/INTERMEDIATE_SRPMS
rm -rf /home/ff/CBL-Mariner/build/make_status/build_srpms.flag
rm -rf /home/ff/CBL-Mariner/build/SRPM_packaging
rm -rf /home/ff/CBL-Mariner/build/INTERMEDIATE_SPECS
rm -rf /home/ff/CBL-Mariner/build/make_status/build_specs.flag
rm -rf /home/ff/CBL-Mariner/build/logs/srpm_expand
rm -rf /home/ff/CBL-Mariner/build/pkg_artifacts
rm -rf /home/ff/CBL-Mariner/build/logs/pkggen/workplan
rm -rf /home/ff/CBL-Mariner/build/rpm_cache
rm -f /home/ff/CBL-Mariner/build/make_status/validate-image-config-pkggen.flag
Verifying no mountpoints present in /home/ff/CBL-Mariner/build/pkg_artifacts/tdnf_cache_worker
/home/ff/CBL-Mariner/toolkit/scripts/safeunmount.sh "/home/ff/CBL-Mariner/build/pkg_artifacts/tdnf_cache_worker" && \
rm -rf /home/ff/CBL-Mariner/build/pkg_artifacts/tdnf_cache_worker
find: ‘/home/ff/CBL-Mariner/build/pkg_artifacts/tdnf_cache_worker’: No such file or directory
rm -rf /home/ff/CBL-Mariner/out/RPMS
rm -rf /home/ff/CBL-Mariner/build/logs/pkggen/failures.txt
rm -rf /home/ff/CBL-Mariner/build/logs/pkggen/rpmbuilding
rm -rf /home/ff/CBL-Mariner/build/make_status/build-rpms.flag
Verifying no mountpoints present in /home/ff/CBL-Mariner/build/worker/chroot
/home/ff/CBL-Mariner/toolkit/scripts/safeunmount.sh "/home/ff/CBL-Mariner/build/worker/chroot" && \
rm -rf /home/ff/CBL-Mariner/build/worker/chroot
find: ‘/home/ff/CBL-Mariner/build/worker/chroot’: No such file or directory
rm -rf /home/ff/CBL-Mariner/out/rpms.tar.gz
rm -rf /home/ff/CBL-Mariner/out/srpms.tar.gz
rm -rf /home/ff/CBL-Mariner/build/make_status/build_srpms.flag
rm -rf /home/ff/CBL-Mariner/build/make_status/imager_disk_output.flag
rm -rf /home/ff/CBL-Mariner/build/make_status/validate-image-config-*
rm -rf /home/ff/CBL-Mariner/out/images/core-efi
rm -rf /home/ff/CBL-Mariner/out/images
Verifying no mountpoints present in /home/ff/CBL-Mariner/build/imagegen
/home/ff/CBL-Mariner/toolkit/scripts/safeunmount.sh "/home/ff/CBL-Mariner/build/imagegen" && \
rm -rf /home/ff/CBL-Mariner/build/imagegen
rm -f /home/ff/CBL-Mariner/out/toolkit-*.tar.gz
rm -rf /home/ff/CBL-Mariner/build/toolkit
rm -rf /home/ff/CBL-Mariner/out
rm -rf /home/ff/CBL-Mariner/build
rm -rf /home/ff/CBL-Mariner/toolkit/out




sudo make image REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/core-efi.json
cd /home/ff/CBL-Mariner/toolkit/tools/ && \
	go test -covermode=atomic -coverprofile=/home/ff/CBL-Mariner/build/tools/internal.test_coverage ./...
?   	microsoft.com/pkggen/boilerplate	[no test files]
ok  	microsoft.com/pkggen/boilerplate/hello	0.007s	coverage: 100.0% of statements
?   	microsoft.com/pkggen/depsearch	[no test files]
?   	microsoft.com/pkggen/grapher	[no test files]
?   	microsoft.com/pkggen/graphoptimizer	[no test files]
?   	microsoft.com/pkggen/graphpkgfetcher	[no test files]
ok  	microsoft.com/pkggen/imageconfigvalidator	0.013s	coverage: 60.4% of statements
?   	microsoft.com/pkggen/imagegen/attendedinstaller	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/primitives/customshortcutlist	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/primitives/navigationbar	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/primitives/progressbar	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/speakuputils	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/uitext	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/uiutils	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views/confirmview	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views/diskview	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views/diskview/autopartitionwidget	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views/diskview/manualpartitionwidget	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views/encryptview	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views/eulaview	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views/finishview	[no test files]
ok  	microsoft.com/pkggen/imagegen/attendedinstaller/views/hostnameview	0.011s	coverage: 43.8% of statements
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views/installationview	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views/installerview	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views/progressview	[no test files]
?   	microsoft.com/pkggen/imagegen/attendedinstaller/views/userview	[no test files]
ok  	microsoft.com/pkggen/imagegen/configuration	0.017s	coverage: 85.3% of statements
ok  	microsoft.com/pkggen/imagegen/diskutils	0.007s	coverage: 0.0% of statements
ok  	microsoft.com/pkggen/imagegen/installutils	0.008s	coverage: 0.3% of statements
?   	microsoft.com/pkggen/imagepkgfetcher	[no test files]
?   	microsoft.com/pkggen/imager	[no test files]
?   	microsoft.com/pkggen/internal/buildpipeline	[no test files]
?   	microsoft.com/pkggen/internal/debugutils	[no test files]
?   	microsoft.com/pkggen/internal/directory	[no test files]
?   	microsoft.com/pkggen/internal/exe	[no test files]
?   	microsoft.com/pkggen/internal/file	[no test files]
?   	microsoft.com/pkggen/internal/jsonutils	[no test files]
?   	microsoft.com/pkggen/internal/logger	[no test files]
?   	microsoft.com/pkggen/internal/logger/hooks/writerhook	[no test files]
?   	microsoft.com/pkggen/internal/network	[no test files]
?   	microsoft.com/pkggen/internal/packagerepo/repocloner	[no test files]
?   	microsoft.com/pkggen/internal/packagerepo/repocloner/rpmrepocloner	[no test files]
?   	microsoft.com/pkggen/internal/packagerepo/repomanager	[no test files]
?   	microsoft.com/pkggen/internal/packagerepo/repomanager/rpmrepomanager	[no test files]
?   	microsoft.com/pkggen/internal/packagerepo/repoutils	[no test files]
ok  	microsoft.com/pkggen/internal/pkggraph	0.038s	coverage: 81.1% of statements
ok  	microsoft.com/pkggen/internal/pkgjson	0.006s	coverage: 93.0% of statements
ok  	microsoft.com/pkggen/internal/randomization	0.266s	coverage: 93.3% of statements
?   	microsoft.com/pkggen/internal/retry	[no test files]
?   	microsoft.com/pkggen/internal/rpm	[no test files]
ERRO[0000] env variable CHROOT_DIR not defined          
PANI[0000] Failed to get chroot dir - env variable CHROOT_DIR not defined 
--- FAIL: TestInitializeShouldCreateRoot (0.00s)
panic: (*logrus.Entry) 0x40001b01c0 [recovered]
	panic: (*logrus.Entry) 0x40001b01c0

goroutine 19 [running]:
testing.tRunner.func1.1(0x20b280, 0x40001b01c0)
	/usr/lib/go-1.15/src/testing/testing.go:1072 +0x240
testing.tRunner.func1(0x4000182900)
	/usr/lib/go-1.15/src/testing/testing.go:1075 +0x34c
panic(0x20b280, 0x40001b01c0)
	/usr/lib/go-1.15/src/runtime/panic.go:969 +0x15c
github.com/sirupsen/logrus.Entry.log(0x40001b0000, 0x400019a210, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x330
github.com/sirupsen/logrus.(*Entry).Log(0x40001b0070, 0x0, 0x40001e3dc8, 0x1, 0x1)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xc4
github.com/sirupsen/logrus.(*Entry).Logf(0x40001b0070, 0x4000000000, 0x2175d6, 0x1d, 0x40001e3e98, 0x1, 0x1)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:333 +0xc8
github.com/sirupsen/logrus.(*Logger).Logf(0x40001b0000, 0x0, 0x2175d6, 0x1d, 0x40001e3e98, 0x1, 0x1)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:146 +0x8c
github.com/sirupsen/logrus.(*Logger).Panicf(...)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:187
microsoft.com/pkggen/internal/safechroot.NewChroot(0x40001bc1e0, 0x5a, 0x0, 0x40001bc1e0)
	/home/ff/CBL-Mariner/toolkit/tools/internal/safechroot/safechroot.go:128 +0x11c
microsoft.com/pkggen/internal/safechroot.TestInitializeShouldCreateRoot(0x4000182900)
	/home/ff/CBL-Mariner/toolkit/tools/internal/safechroot/safechroot_test.go:59 +0x94
testing.tRunner(0x4000182900, 0x223908)
	/usr/lib/go-1.15/src/testing/testing.go:1123 +0xdc
created by testing.(*T).Run
	/usr/lib/go-1.15/src/testing/testing.go:1168 +0x244
FAIL	microsoft.com/pkggen/internal/safechroot	0.008s
?   	microsoft.com/pkggen/internal/shell	[no test files]
?   	microsoft.com/pkggen/internal/sliceutils	[no test files]
ok  	microsoft.com/pkggen/internal/storage	0.011s	coverage: 87.5% of statements
?   	microsoft.com/pkggen/internal/systemdependency	[no test files]
ok  	microsoft.com/pkggen/internal/versioncompare	0.006s	coverage: 98.3% of statements
?   	microsoft.com/pkggen/isomaker	[no test files]
?   	microsoft.com/pkggen/liveinstaller	[no test files]
?   	microsoft.com/pkggen/pkgworker	[no test files]
?   	microsoft.com/pkggen/roast	[no test files]
?   	microsoft.com/pkggen/roast/formats	[no test files]
?   	microsoft.com/pkggen/specreader	[no test files]
?   	microsoft.com/pkggen/srpmpacker	[no test files]
?   	microsoft.com/pkggen/unravel	[no test files]
?   	microsoft.com/pkggen/unravel/formats	[no test files]
?   	microsoft.com/pkggen/validatechroot	[no test files]
FAIL
make: *** [/home/ff/CBL-Mariner/toolkit/scripts/tools.mk:89: /home/ff/CBL-Mariner/build/tools/internal.test_coverage] Error 1

**Comment by christopherco** [comment]
This type of build error could occur if you are building in a Docker environment. Does your environment have the `/.dockerenv` file in the root directory?

**Comment by fozog** [comment]
I don't have any ~/.dockerenv
What shall I have there?

**Comment by christopherco** [comment]
> I don't have any ~/.dockerenv
> What shall I have there?

If you are running in a docker container environment, then docker would have placed the `.dockerenv` file would be under the root directory `/` and not in your user's home dir `~/`. Please double check for the file in the root folder
```
$ ls /.dockerenv
```

The tools do special processing if the `/.dockerenv` file is present and this has tie-ins to requiring `CHROOT_DIR`. I'd like to check if you are actually taking this path or if this is something else.

**Comment by fozog** [comment]
removed /.dockerenv and build works.

So is the docker install in prerequisite a real need? 

docker info

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-40-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 80
 Total Memory: 250.8GiB
 Name: ledge.ozog.com
 ID: OGZX:BMEN:RWBB:MSMI:ZMKS:S244:4FXS:7BG2:NN6O:OP44:CHDM:2UHS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by christopherco** [comment]
> removed /.dockerenv and build works.
Great to hear!

> So is the docker install in prerequisite a real need?
The docker install prereq is needed if you plan on building our initial bootstrap toolchain from scratch. This step is typically not needed since our tools will default to pull the prebuilt toolchain packages from our package server.
