### ISSUE TITLE
Failed to build image

### ISSUE THREAD

**Issue by adamantinum** [microsoft/CBL-Mariner#889]
Hi, I'm trying to generate a VHDX image of CBL-Mariner.
I'm working on Arch Linux but I checked the required tools are installed.
An error occurs during the building process in chroot, it seems blkid executable is not found (manually checking it's in /sbin) but I don't know if it's the cause or a consequence of the issue.
[Here](https://pastebin.com/4pLmFeti) the log.
I have checked in the logs but I have found no other related explanation.
Thank you in advance.

**Comment by PawelWMS** [comment]
Hi, @adamantinum! The only build system CBL-Mariner's toolkit currently supports is Ubuntu 18.04, so my first suggestion would be to try building an image from there.

**Comment by adamantinum** [comment]
Thank you for your reply.
Ubuntu 18.04 seems too outdated: when I try to build the OS it needs glibc 2.32, while version 2.27 is installed...

**Comment by jslobodzian** [comment]
Currently building CBL-Mariner from scratch is only supported on Ubuntu 18.04.

**Comment by adamantinum** [comment]
Neither with Ubuntu 18.04 in Docker?
