### ISSUE TITLE
Make ISO failed with 404 errors

### ISSUE THREAD

**Issue by JoshLuedeman** [microsoft/CBL-Mariner#923]
Running the make statement from documentation to make ISO file. Getting the following error

joluedem@UbuntuServer:~/CBL-Mariner/toolkit$ sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json

Downloading toolchain RPM: kernel-headers-5.10.28.1-4.cm1.noarch.rpm

ERROR: Failed to download toolchain package: kernel-headers-5.10.28.1-4.cm1.noarch.rpm.
ERROR: Last 20 lines from log '/home/joluedem/CBL-Mariner/build/logs/toolchain/downloads/kernel-headers-5.10.28.1-4.cm1.noarch.rpm.log':

        Downloading toolchain RPM: kernel-headers-5.10.28.1-4.cm1.noarch.rpm
        --2021-05-06 21:27:08--  https://packages.microsoft.com/cbl-mariner/1.0/prod/base/x86_64/rpms/kernel-headers-5.10.28.1-4.cm1.noarch.rpm
        Resolving packages.microsoft.com (packages.microsoft.com)... 13.93.224.173
        Connecting to packages.microsoft.com (packages.microsoft.com)|13.93.224.173|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2021-05-06 21:27:12 ERROR 404: Not Found.

        --2021-05-06 21:27:12--  https://packages.microsoft.com/cbl-mariner/1.0/prod/update/x86_64/rpms/kernel-headers-5.10.28.1-4.cm1.noarch.rpm
        Resolving packages.microsoft.com (packages.microsoft.com)... 13.93.224.173
        Connecting to packages.microsoft.com (packages.microsoft.com)|13.93.224.173|:443... connected.
        HTTP request sent, awaiting response... 404 Not Found
        2021-05-06 21:27:12 ERROR 404: Not Found.

Toolchain download failed. See above errors for more details.
/home/joluedem/CBL-Mariner/toolkit/scripts/toolchain.mk:200: recipe for target '/home/joluedem/CBL-Mariner/build/rpm_cache/cache/noarch/kernel-headers-5.10.28.1-4.cm1.noarch.rpm' failed
make: *** [/home/joluedem/CBL-Mariner/build/rpm_cache/cache/noarch/kernel-headers-5.10.28.1-4.cm1.noarch.rpm] Error 1

**Comment by thcrain-msft** [comment]
Hi Josh! Based on the date you opened the issue and the version of kernel-headers the tooling attempted to download, it looks like you were not building from the `1.0-stable` tag. The `1.0-stable` tag is the latest commit that is guaranteed to have RPMS published to `packages.microsoft.com`. I believe checking out that commit is part of the quickstart instructions, but if those instructions are unclear/are missing somewhere, please let us know!

This is conjecture, but you were probably building from the `1.0` branch. At the time you filed the bug, we were in the middle of a release. Normally, the `1.0-stable` tag corresponds with the HEAD of the `1.0` branch. However, during releases, the `1.0-stable` tag will be behind what's in `1.0` as we perform our full testing suite on a `1.0` build prior to announcing the official release and moving up the tag.

**Comment by thcrain-msft** [comment]
Closing, since this is likely a transient issue covered by our documentation. Please feel free to re-open if not.

**Comment by JoshLuedeman** [comment]
Sorry for the delay in getting back to you Thomas. I will retry and see if I have the same issue. Thanks for your response
